// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"catering/voucher/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/voucher/user",
				Handler: GetUserVoucherHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voucher/info",
				Handler: GetVoucherInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voucher/draw",
				Handler: DrawVoucherHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voucher/use",
				Handler: UseVoucherHandler(serverCtx),
			},
		},
	)
}
