// Code generated by goctl. DO NOT EDIT.
package types

import (
	pb "catering/proto/user"
)

type RegisterReq struct {
	Mobie    string `json:"mobie"`
	Password string `json:"password"`
	Smscode  string `json:"smscode"`
}

type RegisterResp struct {
}

type LoginReq struct {
	Mobie     string `json:"mobie"`
	Password  string `json:"password"`
	Smscode   string `json:"smscode"`
	LoginType int64  `json:"loginType"`
}

type LoginResp struct {
	JwtToken
	Info *pb.UserInfo
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResp struct {
	Info *pb.UserInfo
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
	RefreshAfter int64  `json:"refresh_after,omitempty"`
}
