// Code generated by goctl. DO NOT EDIT!
// Source: area.proto

package server

import (
	"context"

	"catering/area/rpc/internal/logic"
	"catering/area/rpc/internal/svc"
	pb "catering/proto/common"
)

type CommonHandlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewCommonHandlerServer(svcCtx *svc.ServiceContext) *CommonHandlerServer {
	return &CommonHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonHandlerServer) GetProvinces(ctx context.Context, in *pb.GetProvincesReq) (*pb.GetProvincesResp, error) {
	l := logic.NewGetProvincesLogic(ctx, s.svcCtx)
	return l.GetProvinces(in)
}

func (s *CommonHandlerServer) GetCitys(ctx context.Context, in *pb.GetCitysReq) (*pb.GetCitysResp, error) {
	l := logic.NewGetCitysLogic(ctx, s.svcCtx)
	return l.GetCitys(in)
}

func (s *CommonHandlerServer) GetDistincts(ctx context.Context, in *pb.GetDistinctsReq) (*pb.GetDistinctsResp, error) {
	l := logic.NewGetDistinctsLogic(ctx, s.svcCtx)
	return l.GetDistincts(in)
}

func (s *CommonHandlerServer) GetProvincesDetail(ctx context.Context, in *pb.GetProvincesDetailReq) (*pb.GetProvincesDetailResp, error) {
	l := logic.NewGetProvincesDetailLogic(ctx, s.svcCtx)
	return l.GetProvincesDetail(in)
}
