// Code generated by goctl. DO NOT EDIT!
// Source: coupon.proto

package server

import (
	"context"

	"catering/coupon/rpc/internal/logic"
	"catering/coupon/rpc/internal/svc"
	proto "catering/proto/coupon"
)

type CouponHandlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewCouponHandlerServer(svcCtx *svc.ServiceContext) *CouponHandlerServer {
	return &CouponHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *CouponHandlerServer) GetUserCoupon(ctx context.Context, in *proto.GetUserCouponReq) (*proto.GetUserCouponResp, error) {
	l := logic.NewGetUserCouponLogic(ctx, s.svcCtx)
	return l.GetUserCoupon(in)
}

func (s *CouponHandlerServer) DrawCoupon(ctx context.Context, in *proto.DrawCouponReq) (*proto.DrawCouponResp, error) {
	l := logic.NewDrawCouponLogic(ctx, s.svcCtx)
	return l.DrawCoupon(in)
}

func (s *CouponHandlerServer) GetCouponInfo(ctx context.Context, in *proto.GetCouponInfoReq) (*proto.GetCouponInfoResp, error) {
	l := logic.NewGetCouponInfoLogic(ctx, s.svcCtx)
	return l.GetCouponInfo(in)
}

func (s *CouponHandlerServer) UseCoupon(ctx context.Context, in *proto.UseCouponReq) (*proto.UseCouponResp, error) {
	l := logic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}
