// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	Mobie                string   `protobuf:"bytes,1,opt,name=mobie,proto3" json:"mobie,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Smscode              string   `protobuf:"bytes,3,opt,name=smscode,proto3" json:"smscode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetMobie() string {
	if m != nil {
		return m.Mobie
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetSmscode() string {
	if m != nil {
		return m.Smscode
	}
	return ""
}

type RegisterResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterResp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type LoginReq struct {
	Mobie                string   `protobuf:"bytes,1,opt,name=mobie,proto3" json:"mobie,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Smscode              string   `protobuf:"bytes,3,opt,name=smscode,proto3" json:"smscode,omitempty"`
	LoginType            int32    `protobuf:"varint,4,opt,name=loginType,proto3" json:"loginType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetMobie() string {
	if m != nil {
		return m.Mobie
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginReq) GetSmscode() string {
	if m != nil {
		return m.Smscode
	}
	return ""
}

func (m *LoginReq) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

type LoginResp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-,optional"`
	XXX_unrecognized     []byte    `json:"-,optional"`
	XXX_sizecache        int32     `json:"-,optional"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserInfoReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfoResp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-,optional"`
	XXX_unrecognized     []byte    `json:"-,optional"`
	XXX_sizecache        int32     `json:"-,optional"`
}

func (m *UserInfoResp) Reset()         { *m = UserInfoResp{} }
func (m *UserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoResp) ProtoMessage()    {}
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResp.Unmarshal(m, b)
}
func (m *UserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResp.Marshal(b, m, deterministic)
}
func (m *UserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResp.Merge(m, src)
}
func (m *UserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoResp.Size(m)
}
func (m *UserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResp proto.InternalMessageInfo

func (m *UserInfoResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserInfo struct {
	Mobie                string   `protobuf:"bytes,1,opt,name=mobie,proto3" json:"mobie,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Platform             int32    `protobuf:"varint,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Uid                  int64    `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	RegistryDid          string   `protobuf:"bytes,8,opt,name=registry_did,json=registryDid,proto3" json:"registry_did,omitempty"`
	RegistryTime         string   `protobuf:"bytes,9,opt,name=registry_time,json=registryTime,proto3" json:"registry_time,omitempty"`
	RecentLoginDid       string   `protobuf:"bytes,10,opt,name=recent_login_did,json=recentLoginDid,proto3" json:"recent_login_did,omitempty"`
	RecentLoginTime      string   `protobuf:"bytes,11,opt,name=recent_login_time,json=recentLoginTime,proto3" json:"recent_login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetMobie() string {
	if m != nil {
		return m.Mobie
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetRegistryDid() string {
	if m != nil {
		return m.RegistryDid
	}
	return ""
}

func (m *UserInfo) GetRegistryTime() string {
	if m != nil {
		return m.RegistryTime
	}
	return ""
}

func (m *UserInfo) GetRecentLoginDid() string {
	if m != nil {
		return m.RecentLoginDid
	}
	return ""
}

func (m *UserInfo) GetRecentLoginTime() string {
	if m != nil {
		return m.RecentLoginTime
	}
	return ""
}

type GetUserAddressReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetUserAddressReq) Reset()         { *m = GetUserAddressReq{} }
func (m *GetUserAddressReq) String() string { return proto.CompactTextString(m) }
func (*GetUserAddressReq) ProtoMessage()    {}
func (*GetUserAddressReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *GetUserAddressReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAddressReq.Unmarshal(m, b)
}
func (m *GetUserAddressReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAddressReq.Marshal(b, m, deterministic)
}
func (m *GetUserAddressReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAddressReq.Merge(m, src)
}
func (m *GetUserAddressReq) XXX_Size() int {
	return xxx_messageInfo_GetUserAddressReq.Size(m)
}
func (m *GetUserAddressReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAddressReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAddressReq proto.InternalMessageInfo

func (m *GetUserAddressReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserAddressResp struct {
	Address              []*UserAddress `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-,optional"`
	XXX_unrecognized     []byte         `json:"-,optional"`
	XXX_sizecache        int32          `json:"-,optional"`
}

func (m *GetUserAddressResp) Reset()         { *m = GetUserAddressResp{} }
func (m *GetUserAddressResp) String() string { return proto.CompactTextString(m) }
func (*GetUserAddressResp) ProtoMessage()    {}
func (*GetUserAddressResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetUserAddressResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAddressResp.Unmarshal(m, b)
}
func (m *GetUserAddressResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAddressResp.Marshal(b, m, deterministic)
}
func (m *GetUserAddressResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAddressResp.Merge(m, src)
}
func (m *GetUserAddressResp) XXX_Size() int {
	return xxx_messageInfo_GetUserAddressResp.Size(m)
}
func (m *GetUserAddressResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAddressResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAddressResp proto.InternalMessageInfo

func (m *GetUserAddressResp) GetAddress() []*UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddressTag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Sort                 int32    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *AddressTag) Reset()         { *m = AddressTag{} }
func (m *AddressTag) String() string { return proto.CompactTextString(m) }
func (*AddressTag) ProtoMessage()    {}
func (*AddressTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *AddressTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressTag.Unmarshal(m, b)
}
func (m *AddressTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressTag.Marshal(b, m, deterministic)
}
func (m *AddressTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressTag.Merge(m, src)
}
func (m *AddressTag) XXX_Size() int {
	return xxx_messageInfo_AddressTag.Size(m)
}
func (m *AddressTag) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressTag.DiscardUnknown(m)
}

var xxx_messageInfo_AddressTag proto.InternalMessageInfo

func (m *AddressTag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddressTag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func (m *AddressTag) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type UserAddress struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiveName          string        `protobuf:"bytes,3,opt,name=receive_name,json=receiveName,proto3" json:"receive_name,omitempty"`
	ReceiveSex           int64         `protobuf:"varint,4,opt,name=receive_sex,json=receiveSex,proto3" json:"receive_sex,omitempty"`
	ReceivePhone         string        `protobuf:"bytes,5,opt,name=receive_phone,json=receivePhone,proto3" json:"receive_phone,omitempty"`
	ProvinceId           int64         `protobuf:"varint,6,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	CityId               int64         `protobuf:"varint,7,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	DistinctId           int64         `protobuf:"varint,8,opt,name=distinct_id,json=distinctId,proto3" json:"distinct_id,omitempty"`
	DetailAddress        string        `protobuf:"bytes,9,opt,name=detail_address,json=detailAddress,proto3" json:"detail_address,omitempty"`
	IsDefault            int32         `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Sort                 int32         `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`
	DeletedTime          string        `protobuf:"bytes,12,opt,name=deletedTime,proto3" json:"deletedTime,omitempty"`
	Tags                 []*AddressTag `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-,optional"`
	XXX_unrecognized     []byte        `json:"-,optional"`
	XXX_sizecache        int32         `json:"-,optional"`
}

func (m *UserAddress) Reset()         { *m = UserAddress{} }
func (m *UserAddress) String() string { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()    {}
func (*UserAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddress.Unmarshal(m, b)
}
func (m *UserAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddress.Marshal(b, m, deterministic)
}
func (m *UserAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddress.Merge(m, src)
}
func (m *UserAddress) XXX_Size() int {
	return xxx_messageInfo_UserAddress.Size(m)
}
func (m *UserAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddress.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddress proto.InternalMessageInfo

func (m *UserAddress) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserAddress) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAddress) GetReceiveName() string {
	if m != nil {
		return m.ReceiveName
	}
	return ""
}

func (m *UserAddress) GetReceiveSex() int64 {
	if m != nil {
		return m.ReceiveSex
	}
	return 0
}

func (m *UserAddress) GetReceivePhone() string {
	if m != nil {
		return m.ReceivePhone
	}
	return ""
}

func (m *UserAddress) GetProvinceId() int64 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *UserAddress) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *UserAddress) GetDistinctId() int64 {
	if m != nil {
		return m.DistinctId
	}
	return 0
}

func (m *UserAddress) GetDetailAddress() string {
	if m != nil {
		return m.DetailAddress
	}
	return ""
}

func (m *UserAddress) GetIsDefault() int32 {
	if m != nil {
		return m.IsDefault
	}
	return 0
}

func (m *UserAddress) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *UserAddress) GetDeletedTime() string {
	if m != nil {
		return m.DeletedTime
	}
	return ""
}

func (m *UserAddress) GetTags() []*AddressTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UserIntegration struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	CurrentIntegration   int64    `protobuf:"varint,3,opt,name=current_integration,json=currentIntegration,proto3" json:"current_integration,omitempty"`
	HistoryIntegration   int64    `protobuf:"varint,4,opt,name=history_integration,json=historyIntegration,proto3" json:"history_integration,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,5,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	CreatedTime          string   `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	ConsumeIntegration   int64    `protobuf:"varint,7,opt,name=consume_integration,json=consumeIntegration,proto3" json:"consume_integration,omitempty"`
	LevelId              int64    `protobuf:"varint,8,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserIntegration) Reset()         { *m = UserIntegration{} }
func (m *UserIntegration) String() string { return proto.CompactTextString(m) }
func (*UserIntegration) ProtoMessage()    {}
func (*UserIntegration) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UserIntegration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIntegration.Unmarshal(m, b)
}
func (m *UserIntegration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIntegration.Marshal(b, m, deterministic)
}
func (m *UserIntegration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIntegration.Merge(m, src)
}
func (m *UserIntegration) XXX_Size() int {
	return xxx_messageInfo_UserIntegration.Size(m)
}
func (m *UserIntegration) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIntegration.DiscardUnknown(m)
}

var xxx_messageInfo_UserIntegration proto.InternalMessageInfo

func (m *UserIntegration) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserIntegration) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserIntegration) GetCurrentIntegration() int64 {
	if m != nil {
		return m.CurrentIntegration
	}
	return 0
}

func (m *UserIntegration) GetHistoryIntegration() int64 {
	if m != nil {
		return m.HistoryIntegration
	}
	return 0
}

func (m *UserIntegration) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *UserIntegration) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *UserIntegration) GetConsumeIntegration() int64 {
	if m != nil {
		return m.ConsumeIntegration
	}
	return 0
}

func (m *UserIntegration) GetLevelId() int64 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

type UserIntegrationLogs struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ChangeType           int64    `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	ChangeValue          int64    `protobuf:"varint,4,opt,name=change_value,json=changeValue,proto3" json:"change_value,omitempty"`
	BeforeValue          int64    `protobuf:"varint,5,opt,name=before_value,json=beforeValue,proto3" json:"before_value,omitempty"`
	AfterValue           int64    `protobuf:"varint,6,opt,name=after_value,json=afterValue,proto3" json:"after_value,omitempty"`
	ChangeTime           string   `protobuf:"bytes,7,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	DeletedTime          int32    `protobuf:"varint,8,opt,name=deleted_time,json=deletedTime,proto3" json:"deleted_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserIntegrationLogs) Reset()         { *m = UserIntegrationLogs{} }
func (m *UserIntegrationLogs) String() string { return proto.CompactTextString(m) }
func (*UserIntegrationLogs) ProtoMessage()    {}
func (*UserIntegrationLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UserIntegrationLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIntegrationLogs.Unmarshal(m, b)
}
func (m *UserIntegrationLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIntegrationLogs.Marshal(b, m, deterministic)
}
func (m *UserIntegrationLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIntegrationLogs.Merge(m, src)
}
func (m *UserIntegrationLogs) XXX_Size() int {
	return xxx_messageInfo_UserIntegrationLogs.Size(m)
}
func (m *UserIntegrationLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIntegrationLogs.DiscardUnknown(m)
}

var xxx_messageInfo_UserIntegrationLogs proto.InternalMessageInfo

func (m *UserIntegrationLogs) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserIntegrationLogs) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserIntegrationLogs) GetChangeType() int64 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *UserIntegrationLogs) GetChangeValue() int64 {
	if m != nil {
		return m.ChangeValue
	}
	return 0
}

func (m *UserIntegrationLogs) GetBeforeValue() int64 {
	if m != nil {
		return m.BeforeValue
	}
	return 0
}

func (m *UserIntegrationLogs) GetAfterValue() int64 {
	if m != nil {
		return m.AfterValue
	}
	return 0
}

func (m *UserIntegrationLogs) GetChangeTime() string {
	if m != nil {
		return m.ChangeTime
	}
	return ""
}

func (m *UserIntegrationLogs) GetDeletedTime() int32 {
	if m != nil {
		return m.DeletedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "proto.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "proto.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "proto.LoginResp")
	proto.RegisterType((*UserInfoReq)(nil), "proto.UserInfoReq")
	proto.RegisterType((*UserInfoResp)(nil), "proto.UserInfoResp")
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*GetUserAddressReq)(nil), "proto.GetUserAddressReq")
	proto.RegisterType((*GetUserAddressResp)(nil), "proto.GetUserAddressResp")
	proto.RegisterType((*AddressTag)(nil), "proto.AddressTag")
	proto.RegisterType((*UserAddress)(nil), "proto.UserAddress")
	proto.RegisterType((*UserIntegration)(nil), "proto.UserIntegration")
	proto.RegisterType((*UserIntegrationLogs)(nil), "proto.UserIntegrationLogs")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xe4, 0x34,
	0x14, 0xa6, 0xf3, 0x3f, 0x27, 0xd3, 0x3f, 0x17, 0x41, 0x3a, 0x02, 0xb5, 0xcd, 0xaa, 0x52, 0xb5,
	0x42, 0xbb, 0xa8, 0x7d, 0x02, 0xd0, 0x4a, 0xbb, 0x23, 0x56, 0x08, 0x85, 0x82, 0xc4, 0x55, 0xe4,
	0xc6, 0x67, 0x52, 0x8b, 0x99, 0x24, 0x6b, 0x7b, 0x86, 0xed, 0x35, 0xcf, 0xc1, 0x35, 0x6f, 0xc3,
	0x93, 0xf0, 0x10, 0xc8, 0xc7, 0x76, 0x92, 0x69, 0x41, 0x5a, 0xa1, 0xbd, 0x8a, 0xcf, 0xe7, 0xcf,
	0xc7, 0xc7, 0xe7, 0xfb, 0x62, 0x03, 0x6c, 0x34, 0xaa, 0x17, 0xb5, 0xaa, 0x4c, 0xc5, 0x86, 0xf4,
	0x49, 0x7e, 0x81, 0x28, 0xc5, 0x42, 0x6a, 0x83, 0x2a, 0xc5, 0x77, 0xec, 0x53, 0x18, 0xae, 0xab,
	0x3b, 0x89, 0xf1, 0xde, 0xf9, 0xde, 0xd5, 0x34, 0x75, 0x01, 0x9b, 0xc3, 0xa4, 0xe6, 0x5a, 0xff,
	0x56, 0x29, 0x11, 0xf7, 0x68, 0xa2, 0x89, 0x59, 0x0c, 0x63, 0xbd, 0xd6, 0x79, 0x25, 0x30, 0xee,
	0xd3, 0x54, 0x08, 0x93, 0x37, 0x30, 0x6b, 0x53, 0xeb, 0x9a, 0x31, 0x18, 0x10, 0xcd, 0xa6, 0x1e,
	0xa6, 0x34, 0x66, 0x47, 0xd0, 0x5f, 0xeb, 0xc2, 0x27, 0xb5, 0x43, 0xcb, 0x12, 0xa8, 0x73, 0x9f,
	0x8c, 0xc6, 0x89, 0x81, 0xc9, 0xdb, 0xaa, 0x90, 0xe5, 0x47, 0xae, 0x90, 0x7d, 0x01, 0xd3, 0x95,
	0xcd, 0x7b, 0xfb, 0x50, 0x63, 0x3c, 0xa0, 0xb2, 0x5a, 0x20, 0xf9, 0x1a, 0xa6, 0x7e, 0x57, 0x5d,
	0xb3, 0x67, 0x30, 0xb0, 0xcd, 0xa3, 0x5d, 0xa3, 0xeb, 0x43, 0xd7, 0xc4, 0x17, 0x3f, 0x69, 0x54,
	0x8b, 0x72, 0x59, 0xa5, 0x34, 0x99, 0x9c, 0x41, 0xd4, 0x20, 0xf8, 0xce, 0x1e, 0x6e, 0x23, 0x05,
	0x2d, 0xe9, 0xa7, 0x76, 0x98, 0xdc, 0xc0, 0xac, 0x25, 0x7c, 0x68, 0xd6, 0xbf, 0x7a, 0x30, 0x09,
	0xd0, 0xff, 0x38, 0xfe, 0x1c, 0x26, 0xa5, 0xcc, 0x7f, 0x2d, 0xf9, 0x3a, 0x9c, 0xbf, 0x89, 0x6d,
	0x85, 0x1a, 0xdf, 0xfb, 0xa3, 0xdb, 0x21, 0x65, 0x5a, 0x71, 0xb3, 0xac, 0xd4, 0x3a, 0x1e, 0x12,
	0xdc, 0xc4, 0xec, 0x33, 0x18, 0xf1, 0x2d, 0x37, 0x5c, 0xc5, 0x23, 0xca, 0xe3, 0xa3, 0x70, 0xce,
	0x71, 0x73, 0x4e, 0x76, 0x01, 0x33, 0x45, 0xd2, 0xab, 0x87, 0x4c, 0x48, 0x11, 0x4f, 0x88, 0x1f,
	0x05, 0xec, 0x95, 0x14, 0xec, 0x19, 0xec, 0x37, 0x14, 0x23, 0xd7, 0x18, 0x4f, 0x89, 0xd3, 0xac,
	0xbb, 0x95, 0x6b, 0x64, 0x57, 0x70, 0xa4, 0x30, 0xc7, 0xd2, 0x64, 0x24, 0x0b, 0xe5, 0x02, 0xe2,
	0x1d, 0x38, 0x9c, 0x04, 0xb2, 0xe9, 0x9e, 0xc3, 0xf1, 0x0e, 0x93, 0x52, 0x46, 0x44, 0x3d, 0xec,
	0x50, 0x6d, 0xd6, 0xe4, 0x12, 0x8e, 0x5f, 0xa3, 0xb1, 0x2d, 0xfd, 0x46, 0x08, 0x85, 0x5a, 0xff,
	0xbb, 0x58, 0xdf, 0x02, 0x7b, 0x4c, 0xd3, 0x35, 0xfb, 0x0a, 0xc6, 0xdc, 0x85, 0xf1, 0xde, 0x79,
	0xff, 0x2a, 0xba, 0x66, 0x1d, 0xd5, 0x02, 0x31, 0x50, 0x92, 0xef, 0x00, 0x3c, 0x76, 0xcb, 0x0b,
	0x76, 0x00, 0xbd, 0x66, 0x8b, 0x9e, 0x14, 0xec, 0x14, 0x26, 0x86, 0x17, 0x19, 0x49, 0xe3, 0x64,
	0x1b, 0x1b, 0x5e, 0x7c, 0x6f, 0x95, 0x61, 0x30, 0xd0, 0x95, 0x32, 0xa4, 0xd8, 0x30, 0xa5, 0x71,
	0xf2, 0x47, 0xdf, 0xf9, 0xcb, 0x67, 0x7c, 0x92, 0xee, 0x73, 0x18, 0x5b, 0xc3, 0x64, 0xd2, 0x99,
	0xa0, 0x9f, 0x8e, 0x6c, 0xb8, 0xf0, 0x72, 0xe4, 0x28, 0xb7, 0x98, 0x75, 0x6c, 0x10, 0x79, 0x8c,
	0xf6, 0x3b, 0x83, 0x10, 0x66, 0xc1, 0x11, 0xfd, 0x14, 0x3c, 0xf4, 0x23, 0xbe, 0x77, 0x7a, 0x39,
	0x42, 0x7d, 0x5f, 0x95, 0x48, 0xee, 0x20, 0xbd, 0x08, 0xfc, 0xc1, 0x62, 0x36, 0x4b, 0xad, 0xaa,
	0xad, 0x2c, 0x73, 0xb4, 0x55, 0x8c, 0x5c, 0x96, 0x00, 0x2d, 0xa8, 0xc4, 0x5c, 0x9a, 0x87, 0xac,
	0xb1, 0xcb, 0xc8, 0x86, 0x0b, 0x61, 0x57, 0x0a, 0xa9, 0x8d, 0x2c, 0x73, 0x93, 0x79, 0xc3, 0xf4,
	0x53, 0x08, 0xd0, 0x42, 0xb0, 0x4b, 0x38, 0x10, 0x68, 0xb8, 0x5c, 0x65, 0xa1, 0xfd, 0xce, 0x30,
	0xfb, 0x0e, 0x0d, 0x3d, 0xf9, 0x12, 0x40, 0xea, 0x4c, 0xe0, 0x92, 0x6f, 0x56, 0x86, 0xbc, 0x32,
	0x4c, 0xa7, 0x52, 0xbf, 0x72, 0x40, 0xd3, 0xd6, 0xa8, 0x6d, 0x2b, 0x3b, 0x87, 0x48, 0xe0, 0x0a,
	0x0d, 0x0a, 0xeb, 0x8e, 0x78, 0xe6, 0x9a, 0xd3, 0x81, 0xd8, 0x25, 0x0c, 0x0c, 0x2f, 0x74, 0xbc,
	0x4f, 0x82, 0x1f, 0x7b, 0xc1, 0x5b, 0x61, 0x53, 0x9a, 0x4e, 0xfe, 0xec, 0xc1, 0xa1, 0xfb, 0x51,
	0x0d, 0x16, 0x8a, 0x1b, 0x59, 0x95, 0x4f, 0x34, 0xf2, 0x36, 0xeb, 0xb5, 0xff, 0xca, 0x4b, 0x38,
	0xc9, 0x37, 0x4a, 0x59, 0xeb, 0xca, 0x76, 0x21, 0x69, 0xd4, 0x4f, 0x99, 0x9f, 0xea, 0xa6, 0x7c,
	0x09, 0x27, 0xf7, 0x52, 0x9b, 0x4a, 0x3d, 0xec, 0x2c, 0x70, 0x92, 0x31, 0x3f, 0xd5, 0x5d, 0x70,
	0x01, 0xb3, 0x4d, 0x2d, 0xb8, 0x41, 0xe1, 0x7e, 0x0b, 0xa7, 0x5c, 0xe4, 0x31, 0x3a, 0xe1, 0x05,
	0xcc, 0x72, 0x85, 0x2d, 0xc5, 0xfd, 0xe0, 0x91, 0xc7, 0x88, 0x62, 0xeb, 0xac, 0x4a, 0xbd, 0x59,
	0xe3, 0xce, 0xb6, 0x63, 0x5f, 0xa7, 0x9b, 0xea, 0x6e, 0x7b, 0x0a, 0x93, 0x15, 0x6e, 0x71, 0xd5,
	0xea, 0x39, 0xa6, 0x78, 0x21, 0x92, 0xdf, 0x7b, 0x70, 0xf2, 0xa8, 0x53, 0x6f, 0xab, 0x42, 0x7f,
	0x40, 0xb7, 0xce, 0x20, 0xca, 0xef, 0x79, 0x59, 0x60, 0x66, 0xec, 0xa5, 0xed, 0xba, 0x04, 0x0e,
	0xb2, 0xb7, 0x36, 0x9d, 0xc4, 0x11, 0xb6, 0x7c, 0xb5, 0x41, 0xdf, 0x16, 0xbf, 0xe8, 0x67, 0x0b,
	0x59, 0xca, 0x1d, 0x2e, 0x2b, 0x15, 0x28, 0x43, 0x47, 0x71, 0x98, 0xa3, 0x9c, 0x41, 0xc4, 0x97,
	0x06, 0x95, 0x67, 0x78, 0x23, 0x13, 0xd4, 0x10, 0x42, 0x1d, 0xb6, 0x5f, 0x63, 0xea, 0x57, 0xa8,
	0xc3, 0x77, 0xd4, 0x5b, 0xc8, 0x31, 0x26, 0xe4, 0xb8, 0xae, 0xad, 0xae, 0xff, 0xde, 0x73, 0xff,
	0xf3, 0x1b, 0x5e, 0x8a, 0x15, 0x2a, 0x76, 0x03, 0x93, 0xf0, 0x60, 0xb2, 0x70, 0xab, 0x74, 0x1e,
	0xe7, 0xf9, 0xc9, 0x13, 0x4c, 0xd7, 0xec, 0x39, 0x0c, 0xe9, 0x66, 0x63, 0xe1, 0xf5, 0x08, 0x2f,
	0xe5, 0xfc, 0x68, 0x17, 0xd0, 0xb5, 0xdd, 0xa0, 0x79, 0x48, 0xd8, 0xe3, 0xc7, 0xa6, 0xb3, 0xc1,
	0xce, 0x1b, 0xf5, 0x1a, 0x0e, 0x76, 0xaf, 0x41, 0x16, 0x7b, 0xda, 0x93, 0x4b, 0x74, 0x7e, 0xfa,
	0x1f, 0x33, 0xba, 0x4e, 0x3e, 0xb9, 0x1b, 0xd1, 0xdc, 0xcd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x21, 0xaa, 0xb7, 0x43, 0x86, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserHandlerClient is the client API for UserHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserHandlerClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	GetUserAddress(ctx context.Context, in *GetUserAddressReq, opts ...grpc.CallOption) (*GetUserAddressResp, error)
}

type userHandlerClient struct {
	cc *grpc.ClientConn
}

func NewUserHandlerClient(cc *grpc.ClientConn) UserHandlerClient {
	return &userHandlerClient{cc}
}

func (c *userHandlerClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/proto.UserHandler/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/proto.UserHandler/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, "/proto.UserHandler/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) GetUserAddress(ctx context.Context, in *GetUserAddressReq, opts ...grpc.CallOption) (*GetUserAddressResp, error) {
	out := new(GetUserAddressResp)
	err := c.cc.Invoke(ctx, "/proto.UserHandler/GetUserAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserHandlerServer is the server API for UserHandler service.
type UserHandlerServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	UserInfo(context.Context, *UserInfoReq) (*UserInfoResp, error)
	GetUserAddress(context.Context, *GetUserAddressReq) (*GetUserAddressResp, error)
}

// UnimplementedUserHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedUserHandlerServer struct {
}

func (*UnimplementedUserHandlerServer) Register(ctx context.Context, req *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserHandlerServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserHandlerServer) UserInfo(ctx context.Context, req *UserInfoReq) (*UserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedUserHandlerServer) GetUserAddress(ctx context.Context, req *GetUserAddressReq) (*GetUserAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAddress not implemented")
}

func RegisterUserHandlerServer(s *grpc.Server, srv UserHandlerServer) {
	s.RegisterService(&_UserHandler_serviceDesc, srv)
}

func _UserHandler_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserHandler/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserHandler/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserHandler/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).UserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_GetUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).GetUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserHandler/GetUserAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).GetUserAddress(ctx, req.(*GetUserAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserHandler",
	HandlerType: (*UserHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserHandler_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserHandler_Login_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _UserHandler_UserInfo_Handler,
		},
		{
			MethodName: "GetUserAddress",
			Handler:    _UserHandler_GetUserAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
