// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voucher.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetVoucherInfoReq struct {
	VoucherId            int64    `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetVoucherInfoReq) Reset()         { *m = GetVoucherInfoReq{} }
func (m *GetVoucherInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetVoucherInfoReq) ProtoMessage()    {}
func (*GetVoucherInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{0}
}

func (m *GetVoucherInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVoucherInfoReq.Unmarshal(m, b)
}
func (m *GetVoucherInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVoucherInfoReq.Marshal(b, m, deterministic)
}
func (m *GetVoucherInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVoucherInfoReq.Merge(m, src)
}
func (m *GetVoucherInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetVoucherInfoReq.Size(m)
}
func (m *GetVoucherInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVoucherInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVoucherInfoReq proto.InternalMessageInfo

func (m *GetVoucherInfoReq) GetVoucherId() int64 {
	if m != nil {
		return m.VoucherId
	}
	return 0
}

type GetVoucherInfoResp struct {
	Voucher              *Voucher `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetVoucherInfoResp) Reset()         { *m = GetVoucherInfoResp{} }
func (m *GetVoucherInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetVoucherInfoResp) ProtoMessage()    {}
func (*GetVoucherInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{1}
}

func (m *GetVoucherInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVoucherInfoResp.Unmarshal(m, b)
}
func (m *GetVoucherInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVoucherInfoResp.Marshal(b, m, deterministic)
}
func (m *GetVoucherInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVoucherInfoResp.Merge(m, src)
}
func (m *GetVoucherInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetVoucherInfoResp.Size(m)
}
func (m *GetVoucherInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVoucherInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVoucherInfoResp proto.InternalMessageInfo

func (m *GetVoucherInfoResp) GetVoucher() *Voucher {
	if m != nil {
		return m.Voucher
	}
	return nil
}

type GetUserVoucherReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Begin                int32    `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetUserVoucherReq) Reset()         { *m = GetUserVoucherReq{} }
func (m *GetUserVoucherReq) String() string { return proto.CompactTextString(m) }
func (*GetUserVoucherReq) ProtoMessage()    {}
func (*GetUserVoucherReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{2}
}

func (m *GetUserVoucherReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVoucherReq.Unmarshal(m, b)
}
func (m *GetUserVoucherReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVoucherReq.Marshal(b, m, deterministic)
}
func (m *GetUserVoucherReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVoucherReq.Merge(m, src)
}
func (m *GetUserVoucherReq) XXX_Size() int {
	return xxx_messageInfo_GetUserVoucherReq.Size(m)
}
func (m *GetUserVoucherReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVoucherReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVoucherReq proto.InternalMessageInfo

func (m *GetUserVoucherReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserVoucherReq) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *GetUserVoucherReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserVoucherResp struct {
	Vouchers             []*UserVoucher `protobuf:"bytes,1,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-,optional"`
	XXX_unrecognized     []byte         `json:"-,optional"`
	XXX_sizecache        int32          `json:"-,optional"`
}

func (m *GetUserVoucherResp) Reset()         { *m = GetUserVoucherResp{} }
func (m *GetUserVoucherResp) String() string { return proto.CompactTextString(m) }
func (*GetUserVoucherResp) ProtoMessage()    {}
func (*GetUserVoucherResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{3}
}

func (m *GetUserVoucherResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVoucherResp.Unmarshal(m, b)
}
func (m *GetUserVoucherResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVoucherResp.Marshal(b, m, deterministic)
}
func (m *GetUserVoucherResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVoucherResp.Merge(m, src)
}
func (m *GetUserVoucherResp) XXX_Size() int {
	return xxx_messageInfo_GetUserVoucherResp.Size(m)
}
func (m *GetUserVoucherResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVoucherResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVoucherResp proto.InternalMessageInfo

func (m *GetUserVoucherResp) GetVouchers() []*UserVoucher {
	if m != nil {
		return m.Vouchers
	}
	return nil
}

type DrawVoucherReq struct {
	VoucherId            int64    `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *DrawVoucherReq) Reset()         { *m = DrawVoucherReq{} }
func (m *DrawVoucherReq) String() string { return proto.CompactTextString(m) }
func (*DrawVoucherReq) ProtoMessage()    {}
func (*DrawVoucherReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{4}
}

func (m *DrawVoucherReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawVoucherReq.Unmarshal(m, b)
}
func (m *DrawVoucherReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawVoucherReq.Marshal(b, m, deterministic)
}
func (m *DrawVoucherReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawVoucherReq.Merge(m, src)
}
func (m *DrawVoucherReq) XXX_Size() int {
	return xxx_messageInfo_DrawVoucherReq.Size(m)
}
func (m *DrawVoucherReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawVoucherReq.DiscardUnknown(m)
}

var xxx_messageInfo_DrawVoucherReq proto.InternalMessageInfo

func (m *DrawVoucherReq) GetVoucherId() int64 {
	if m != nil {
		return m.VoucherId
	}
	return 0
}

func (m *DrawVoucherReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DrawVoucherReq) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DrawVoucherResp struct {
	Vouchers             []*UserVoucher `protobuf:"bytes,1,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-,optional"`
	XXX_unrecognized     []byte         `json:"-,optional"`
	XXX_sizecache        int32          `json:"-,optional"`
}

func (m *DrawVoucherResp) Reset()         { *m = DrawVoucherResp{} }
func (m *DrawVoucherResp) String() string { return proto.CompactTextString(m) }
func (*DrawVoucherResp) ProtoMessage()    {}
func (*DrawVoucherResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{5}
}

func (m *DrawVoucherResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawVoucherResp.Unmarshal(m, b)
}
func (m *DrawVoucherResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawVoucherResp.Marshal(b, m, deterministic)
}
func (m *DrawVoucherResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawVoucherResp.Merge(m, src)
}
func (m *DrawVoucherResp) XXX_Size() int {
	return xxx_messageInfo_DrawVoucherResp.Size(m)
}
func (m *DrawVoucherResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawVoucherResp.DiscardUnknown(m)
}

var xxx_messageInfo_DrawVoucherResp proto.InternalMessageInfo

func (m *DrawVoucherResp) GetVouchers() []*UserVoucher {
	if m != nil {
		return m.Vouchers
	}
	return nil
}

type UseVoucherReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	VoucherId            int64    `protobuf:"varint,2,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	UserVoucherId        int64    `protobuf:"varint,3,opt,name=user_voucher_id,json=userVoucherId,proto3" json:"user_voucher_id,omitempty"`
	OrderId              int64    `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UseVoucherReq) Reset()         { *m = UseVoucherReq{} }
func (m *UseVoucherReq) String() string { return proto.CompactTextString(m) }
func (*UseVoucherReq) ProtoMessage()    {}
func (*UseVoucherReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{6}
}

func (m *UseVoucherReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseVoucherReq.Unmarshal(m, b)
}
func (m *UseVoucherReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseVoucherReq.Marshal(b, m, deterministic)
}
func (m *UseVoucherReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseVoucherReq.Merge(m, src)
}
func (m *UseVoucherReq) XXX_Size() int {
	return xxx_messageInfo_UseVoucherReq.Size(m)
}
func (m *UseVoucherReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UseVoucherReq.DiscardUnknown(m)
}

var xxx_messageInfo_UseVoucherReq proto.InternalMessageInfo

func (m *UseVoucherReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UseVoucherReq) GetVoucherId() int64 {
	if m != nil {
		return m.VoucherId
	}
	return 0
}

func (m *UseVoucherReq) GetUserVoucherId() int64 {
	if m != nil {
		return m.UserVoucherId
	}
	return 0
}

func (m *UseVoucherReq) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type UseVoucherResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UseVoucherResp) Reset()         { *m = UseVoucherResp{} }
func (m *UseVoucherResp) String() string { return proto.CompactTextString(m) }
func (*UseVoucherResp) ProtoMessage()    {}
func (*UseVoucherResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{7}
}

func (m *UseVoucherResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseVoucherResp.Unmarshal(m, b)
}
func (m *UseVoucherResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseVoucherResp.Marshal(b, m, deterministic)
}
func (m *UseVoucherResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseVoucherResp.Merge(m, src)
}
func (m *UseVoucherResp) XXX_Size() int {
	return xxx_messageInfo_UseVoucherResp.Size(m)
}
func (m *UseVoucherResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UseVoucherResp.DiscardUnknown(m)
}

var xxx_messageInfo_UseVoucherResp proto.InternalMessageInfo

type UserVoucher struct {
	UserVoucherId        int64    `protobuf:"varint,1,opt,name=user_voucher_id,json=userVoucherId,proto3" json:"user_voucher_id,omitempty"`
	GetTime              string   `protobuf:"bytes,2,opt,name=get_time,json=getTime,proto3" json:"get_time,omitempty"`
	UseBeginTime         string   `protobuf:"bytes,3,opt,name=use_begin_time,json=useBeginTime,proto3" json:"use_begin_time,omitempty"`
	UseEndTime           string   `protobuf:"bytes,4,opt,name=use_end_time,json=useEndTime,proto3" json:"use_end_time,omitempty"`
	UseStatus            int32    `protobuf:"varint,5,opt,name=use_status,json=useStatus,proto3" json:"use_status,omitempty"`
	Voucher              *Voucher `protobuf:"bytes,6,opt,name=voucher,proto3" json:"voucher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserVoucher) Reset()         { *m = UserVoucher{} }
func (m *UserVoucher) String() string { return proto.CompactTextString(m) }
func (*UserVoucher) ProtoMessage()    {}
func (*UserVoucher) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{8}
}

func (m *UserVoucher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVoucher.Unmarshal(m, b)
}
func (m *UserVoucher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVoucher.Marshal(b, m, deterministic)
}
func (m *UserVoucher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVoucher.Merge(m, src)
}
func (m *UserVoucher) XXX_Size() int {
	return xxx_messageInfo_UserVoucher.Size(m)
}
func (m *UserVoucher) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVoucher.DiscardUnknown(m)
}

var xxx_messageInfo_UserVoucher proto.InternalMessageInfo

func (m *UserVoucher) GetUserVoucherId() int64 {
	if m != nil {
		return m.UserVoucherId
	}
	return 0
}

func (m *UserVoucher) GetGetTime() string {
	if m != nil {
		return m.GetTime
	}
	return ""
}

func (m *UserVoucher) GetUseBeginTime() string {
	if m != nil {
		return m.UseBeginTime
	}
	return ""
}

func (m *UserVoucher) GetUseEndTime() string {
	if m != nil {
		return m.UseEndTime
	}
	return ""
}

func (m *UserVoucher) GetUseStatus() int32 {
	if m != nil {
		return m.UseStatus
	}
	return 0
}

func (m *UserVoucher) GetVoucher() *Voucher {
	if m != nil {
		return m.Voucher
	}
	return nil
}

type Voucher struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VoucherName          string   `protobuf:"bytes,2,opt,name=voucher_name,json=voucherName,proto3" json:"voucher_name,omitempty"`
	LeastUsePrice        int32    `protobuf:"varint,3,opt,name=least_use_price,json=leastUsePrice,proto3" json:"least_use_price,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PicUrl               string   `protobuf:"bytes,5,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	UseType              int32    `protobuf:"varint,6,opt,name=use_type,json=useType,proto3" json:"use_type,omitempty"`
	GetBeginTime         string   `protobuf:"bytes,7,opt,name=get_begin_time,json=getBeginTime,proto3" json:"get_begin_time,omitempty"`
	GetEndTime           string   `protobuf:"bytes,8,opt,name=get_end_time,json=getEndTime,proto3" json:"get_end_time,omitempty"`
	UseBeginTime         string   `protobuf:"bytes,9,opt,name=use_begin_time,json=useBeginTime,proto3" json:"use_begin_time,omitempty"`
	UseEndTime           string   `protobuf:"bytes,10,opt,name=use_end_time,json=useEndTime,proto3" json:"use_end_time,omitempty"`
	Status               int32    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	TotalCount           int32    `protobuf:"varint,12,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RemainCount          int32    `protobuf:"varint,13,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`
	GetCount             int32    `protobuf:"varint,14,opt,name=get_count,json=getCount,proto3" json:"get_count,omitempty"`
	ValidTimeType        int32    `protobuf:"varint,15,opt,name=valid_time_type,json=validTimeType,proto3" json:"valid_time_type,omitempty"`
	ValidDay             int32    `protobuf:"varint,16,opt,name=valid_day,json=validDay,proto3" json:"valid_day,omitempty"`
	Description          string   `protobuf:"bytes,17,opt,name=description,proto3" json:"description,omitempty"`
	GetType              int32    `protobuf:"varint,18,opt,name=get_type,json=getType,proto3" json:"get_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *Voucher) Reset()         { *m = Voucher{} }
func (m *Voucher) String() string { return proto.CompactTextString(m) }
func (*Voucher) ProtoMessage()    {}
func (*Voucher) Descriptor() ([]byte, []int) {
	return fileDescriptor_a22a9b0d3335ba25, []int{9}
}

func (m *Voucher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voucher.Unmarshal(m, b)
}
func (m *Voucher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voucher.Marshal(b, m, deterministic)
}
func (m *Voucher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voucher.Merge(m, src)
}
func (m *Voucher) XXX_Size() int {
	return xxx_messageInfo_Voucher.Size(m)
}
func (m *Voucher) XXX_DiscardUnknown() {
	xxx_messageInfo_Voucher.DiscardUnknown(m)
}

var xxx_messageInfo_Voucher proto.InternalMessageInfo

func (m *Voucher) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Voucher) GetVoucherName() string {
	if m != nil {
		return m.VoucherName
	}
	return ""
}

func (m *Voucher) GetLeastUsePrice() int32 {
	if m != nil {
		return m.LeastUsePrice
	}
	return 0
}

func (m *Voucher) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Voucher) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *Voucher) GetUseType() int32 {
	if m != nil {
		return m.UseType
	}
	return 0
}

func (m *Voucher) GetGetBeginTime() string {
	if m != nil {
		return m.GetBeginTime
	}
	return ""
}

func (m *Voucher) GetGetEndTime() string {
	if m != nil {
		return m.GetEndTime
	}
	return ""
}

func (m *Voucher) GetUseBeginTime() string {
	if m != nil {
		return m.UseBeginTime
	}
	return ""
}

func (m *Voucher) GetUseEndTime() string {
	if m != nil {
		return m.UseEndTime
	}
	return ""
}

func (m *Voucher) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Voucher) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Voucher) GetRemainCount() int32 {
	if m != nil {
		return m.RemainCount
	}
	return 0
}

func (m *Voucher) GetGetCount() int32 {
	if m != nil {
		return m.GetCount
	}
	return 0
}

func (m *Voucher) GetValidTimeType() int32 {
	if m != nil {
		return m.ValidTimeType
	}
	return 0
}

func (m *Voucher) GetValidDay() int32 {
	if m != nil {
		return m.ValidDay
	}
	return 0
}

func (m *Voucher) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Voucher) GetGetType() int32 {
	if m != nil {
		return m.GetType
	}
	return 0
}

func init() {
	proto.RegisterType((*GetVoucherInfoReq)(nil), "proto.GetVoucherInfoReq")
	proto.RegisterType((*GetVoucherInfoResp)(nil), "proto.GetVoucherInfoResp")
	proto.RegisterType((*GetUserVoucherReq)(nil), "proto.GetUserVoucherReq")
	proto.RegisterType((*GetUserVoucherResp)(nil), "proto.GetUserVoucherResp")
	proto.RegisterType((*DrawVoucherReq)(nil), "proto.DrawVoucherReq")
	proto.RegisterType((*DrawVoucherResp)(nil), "proto.DrawVoucherResp")
	proto.RegisterType((*UseVoucherReq)(nil), "proto.UseVoucherReq")
	proto.RegisterType((*UseVoucherResp)(nil), "proto.UseVoucherResp")
	proto.RegisterType((*UserVoucher)(nil), "proto.UserVoucher")
	proto.RegisterType((*Voucher)(nil), "proto.Voucher")
}

func init() { proto.RegisterFile("voucher.proto", fileDescriptor_a22a9b0d3335ba25) }

var fileDescriptor_a22a9b0d3335ba25 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0xf3, 0xe7, 0x7a, 0xdc, 0x38, 0xed, 0xaa, 0xed, 0xe7, 0xb6, 0xaa, 0xbe, 0x60, 0xa1,
	0x2a, 0x57, 0xbd, 0x08, 0x57, 0x48, 0x08, 0x09, 0x68, 0x05, 0xb9, 0x41, 0x60, 0x1a, 0xb8, 0xb4,
	0xdc, 0x78, 0x08, 0x96, 0x12, 0x7b, 0xeb, 0x5d, 0x17, 0xe5, 0x9a, 0x87, 0xe0, 0x59, 0x78, 0x1c,
	0xde, 0x04, 0xed, 0xec, 0x3a, 0xb1, 0xfb, 0x27, 0xc4, 0x55, 0x3b, 0x67, 0x8e, 0x77, 0xce, 0x9c,
	0x99, 0x4e, 0xa1, 0x7f, 0x93, 0x97, 0xb3, 0x6f, 0x58, 0x9c, 0xf1, 0x22, 0x97, 0x39, 0xeb, 0xd2,
	0x8f, 0x60, 0x0c, 0xbb, 0x6f, 0x51, 0x7e, 0xd6, 0xa9, 0x49, 0xf6, 0x35, 0x0f, 0xf1, 0x9a, 0x9d,
	0x00, 0x18, 0x72, 0x94, 0x26, 0xbe, 0x35, 0xb4, 0x46, 0xed, 0xd0, 0x31, 0xc8, 0x24, 0x09, 0x5e,
	0x02, 0xbb, 0xfd, 0x8d, 0xe0, 0x6c, 0x04, 0xb6, 0xa1, 0xd0, 0x17, 0xee, 0xd8, 0xd3, 0x95, 0xce,
	0x0c, 0x31, 0xac, 0xd2, 0xc1, 0x47, 0xaa, 0x39, 0x15, 0x58, 0x54, 0x29, 0xbc, 0x66, 0x3b, 0xd0,
	0x2e, 0xd7, 0xc5, 0xd4, 0xaf, 0x6c, 0x0f, 0xba, 0x57, 0x38, 0x4f, 0x33, 0xbf, 0x35, 0xb4, 0x46,
	0xdd, 0x50, 0x07, 0x0a, 0x9d, 0xe5, 0x65, 0x26, 0xfd, 0xb6, 0x46, 0x29, 0x08, 0xce, 0x49, 0x52,
	0xe3, 0x49, 0xc1, 0xd9, 0x19, 0x6c, 0x99, 0x9a, 0xc2, 0xb7, 0x86, 0xed, 0x91, 0x3b, 0x66, 0x46,
	0x53, 0x9d, 0xb9, 0xe6, 0x04, 0x5f, 0xc0, 0x3b, 0x2f, 0xe2, 0xef, 0x35, 0x55, 0x8f, 0x3b, 0x51,
	0x89, 0x6e, 0x35, 0x44, 0x6f, 0xe4, 0xb5, 0x2b, 0x79, 0xaf, 0x60, 0xd0, 0x78, 0xf8, 0x1f, 0xb4,
	0xfd, 0xb0, 0xa0, 0x3f, 0x15, 0xf8, 0xa8, 0x63, 0x4d, 0xb5, 0xad, 0xdb, 0x6a, 0x4f, 0x61, 0x50,
	0x0a, 0x2c, 0xa2, 0x1a, 0x47, 0xab, 0xec, 0x97, 0x9b, 0x92, 0x93, 0x84, 0x1d, 0xc2, 0x56, 0x5e,
	0x24, 0x9a, 0xd0, 0x21, 0x82, 0x4d, 0xf1, 0x24, 0x09, 0x76, 0xc0, 0xab, 0x8b, 0x10, 0x3c, 0xf8,
	0x6d, 0x81, 0x5b, 0x53, 0x7c, 0x5f, 0x11, 0xeb, 0x81, 0x22, 0x73, 0x94, 0x91, 0x4c, 0x97, 0x48,
	0x4a, 0x9d, 0xd0, 0x9e, 0xa3, 0xbc, 0x4c, 0x97, 0xc8, 0x9e, 0x82, 0x57, 0x0a, 0x8c, 0x68, 0xde,
	0x9a, 0xd0, 0x26, 0xc2, 0x76, 0x29, 0xf0, 0xb5, 0x02, 0x89, 0x35, 0x04, 0x15, 0x47, 0x98, 0x25,
	0x9a, 0xd3, 0x21, 0x0e, 0x94, 0x02, 0x2f, 0xb2, 0x84, 0x18, 0x27, 0xa0, 0xa2, 0x48, 0xc8, 0x58,
	0x96, 0xc2, 0xef, 0xd2, 0xbe, 0x38, 0xa5, 0xc0, 0x4f, 0x04, 0xd4, 0x17, 0xb6, 0xf7, 0xf8, 0xc2,
	0xfe, 0xea, 0x80, 0x5d, 0xf5, 0xe7, 0x41, 0x6b, 0xdd, 0x52, 0x2b, 0x4d, 0xd8, 0x13, 0xd8, 0xae,
	0x5a, 0xcd, 0xe2, 0x75, 0x2f, 0xae, 0xc1, 0xde, 0xc7, 0x4b, 0x54, 0x96, 0x2c, 0x30, 0x16, 0x32,
	0x52, 0x6a, 0x78, 0x91, 0xce, 0xd0, 0x2c, 0x6f, 0x9f, 0xe0, 0xa9, 0xc0, 0x0f, 0x0a, 0x54, 0xbb,
	0xa3, 0xb3, 0x1d, 0xbd, 0xda, 0x14, 0xb0, 0xff, 0xc0, 0xe6, 0xe9, 0x2c, 0x2a, 0x8b, 0x05, 0xb5,
	0xe0, 0x84, 0x3d, 0x9e, 0xce, 0xa6, 0xc5, 0x42, 0x39, 0xa8, 0x1e, 0x94, 0x2b, 0x8e, 0xd4, 0x40,
	0x37, 0xb4, 0x4b, 0x81, 0x97, 0x2b, 0x4e, 0x0e, 0x2a, 0x73, 0x6b, 0x0e, 0xda, 0xda, 0xc1, 0x39,
	0xca, 0x86, 0x83, 0x8a, 0xb5, 0x76, 0x70, 0x4b, 0x3b, 0x38, 0x47, 0x59, 0x39, 0x78, 0x77, 0x12,
	0xce, 0x5f, 0x4c, 0x02, 0xee, 0x4c, 0xe2, 0x00, 0x7a, 0x66, 0x0a, 0x2e, 0x09, 0x35, 0x11, 0xfb,
	0x1f, 0x5c, 0x99, 0xcb, 0x78, 0x11, 0xe9, 0xbf, 0x99, 0x6d, 0x4a, 0x02, 0x41, 0x6f, 0x14, 0xa2,
	0xdc, 0x2d, 0x70, 0x19, 0xa7, 0x99, 0x61, 0xf4, 0x89, 0xe1, 0x6a, 0x4c, 0x53, 0x8e, 0xc1, 0x51,
	0x5d, 0xe8, 0xbc, 0x47, 0x79, 0xb5, 0x59, 0x3a, 0x79, 0x0a, 0x83, 0x9b, 0x78, 0x91, 0x6a, 0x61,
	0xda, 0xaa, 0x81, 0xb6, 0x9e, 0x60, 0x25, 0x8e, 0x0c, 0x3b, 0x06, 0x47, 0xf3, 0x92, 0x78, 0xe5,
	0xef, 0xe8, 0x47, 0x08, 0x38, 0x8f, 0x57, 0x6c, 0x08, 0x6e, 0x82, 0x62, 0x56, 0xa4, 0x5c, 0xa6,
	0x79, 0xe6, 0xef, 0xea, 0x09, 0xd7, 0xa0, 0xf5, 0x32, 0xab, 0xf7, 0x99, 0x1e, 0x85, 0x5a, 0xe6,
	0x15, 0xc7, 0xf1, 0xcf, 0x16, 0x78, 0x66, 0x77, 0xde, 0xc5, 0x59, 0xb2, 0xc0, 0x82, 0x5d, 0x80,
	0xd7, 0x3c, 0x56, 0xcc, 0x37, 0x9b, 0x77, 0xe7, 0x2c, 0x1e, 0x1d, 0x3e, 0x90, 0x11, 0x9c, 0xbd,
	0x00, 0xb7, 0x76, 0x54, 0xd8, 0xbe, 0x61, 0x36, 0x2f, 0xd8, 0xd1, 0xc1, 0x7d, 0xb0, 0xe0, 0x46,
	0x44, 0xed, 0x88, 0xd7, 0x45, 0x34, 0xff, 0x1f, 0xd4, 0x45, 0xdc, 0xbe, 0xfa, 0xcf, 0x01, 0x36,
	0x07, 0x81, 0xed, 0x6d, 0x4e, 0x58, 0x4d, 0xc2, 0xfe, 0x3d, 0xa8, 0xe0, 0x57, 0x3d, 0x42, 0x9f,
	0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xce, 0xf2, 0x92, 0x27, 0x99, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VoucherHandlerClient is the client API for VoucherHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VoucherHandlerClient interface {
	GetUserVoucher(ctx context.Context, in *GetUserVoucherReq, opts ...grpc.CallOption) (*GetUserVoucherResp, error)
	DrawVoucher(ctx context.Context, in *DrawVoucherReq, opts ...grpc.CallOption) (*DrawVoucherResp, error)
	GetVoucherInfo(ctx context.Context, in *GetVoucherInfoReq, opts ...grpc.CallOption) (*GetVoucherInfoResp, error)
	UseVoucher(ctx context.Context, in *UseVoucherReq, opts ...grpc.CallOption) (*UseVoucherResp, error)
}

type voucherHandlerClient struct {
	cc *grpc.ClientConn
}

func NewVoucherHandlerClient(cc *grpc.ClientConn) VoucherHandlerClient {
	return &voucherHandlerClient{cc}
}

func (c *voucherHandlerClient) GetUserVoucher(ctx context.Context, in *GetUserVoucherReq, opts ...grpc.CallOption) (*GetUserVoucherResp, error) {
	out := new(GetUserVoucherResp)
	err := c.cc.Invoke(ctx, "/proto.VoucherHandler/GetUserVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherHandlerClient) DrawVoucher(ctx context.Context, in *DrawVoucherReq, opts ...grpc.CallOption) (*DrawVoucherResp, error) {
	out := new(DrawVoucherResp)
	err := c.cc.Invoke(ctx, "/proto.VoucherHandler/DrawVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherHandlerClient) GetVoucherInfo(ctx context.Context, in *GetVoucherInfoReq, opts ...grpc.CallOption) (*GetVoucherInfoResp, error) {
	out := new(GetVoucherInfoResp)
	err := c.cc.Invoke(ctx, "/proto.VoucherHandler/GetVoucherInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherHandlerClient) UseVoucher(ctx context.Context, in *UseVoucherReq, opts ...grpc.CallOption) (*UseVoucherResp, error) {
	out := new(UseVoucherResp)
	err := c.cc.Invoke(ctx, "/proto.VoucherHandler/UseVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoucherHandlerServer is the server API for VoucherHandler service.
type VoucherHandlerServer interface {
	GetUserVoucher(context.Context, *GetUserVoucherReq) (*GetUserVoucherResp, error)
	DrawVoucher(context.Context, *DrawVoucherReq) (*DrawVoucherResp, error)
	GetVoucherInfo(context.Context, *GetVoucherInfoReq) (*GetVoucherInfoResp, error)
	UseVoucher(context.Context, *UseVoucherReq) (*UseVoucherResp, error)
}

// UnimplementedVoucherHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedVoucherHandlerServer struct {
}

func (*UnimplementedVoucherHandlerServer) GetUserVoucher(ctx context.Context, req *GetUserVoucherReq) (*GetUserVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVoucher not implemented")
}
func (*UnimplementedVoucherHandlerServer) DrawVoucher(ctx context.Context, req *DrawVoucherReq) (*DrawVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrawVoucher not implemented")
}
func (*UnimplementedVoucherHandlerServer) GetVoucherInfo(ctx context.Context, req *GetVoucherInfoReq) (*GetVoucherInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucherInfo not implemented")
}
func (*UnimplementedVoucherHandlerServer) UseVoucher(ctx context.Context, req *UseVoucherReq) (*UseVoucherResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseVoucher not implemented")
}

func RegisterVoucherHandlerServer(s *grpc.Server, srv VoucherHandlerServer) {
	s.RegisterService(&_VoucherHandler_serviceDesc, srv)
}

func _VoucherHandler_GetUserVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherHandlerServer).GetUserVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VoucherHandler/GetUserVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherHandlerServer).GetUserVoucher(ctx, req.(*GetUserVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherHandler_DrawVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherHandlerServer).DrawVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VoucherHandler/DrawVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherHandlerServer).DrawVoucher(ctx, req.(*DrawVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherHandler_GetVoucherInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoucherInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherHandlerServer).GetVoucherInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VoucherHandler/GetVoucherInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherHandlerServer).GetVoucherInfo(ctx, req.(*GetVoucherInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherHandler_UseVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseVoucherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherHandlerServer).UseVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VoucherHandler/UseVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherHandlerServer).UseVoucher(ctx, req.(*UseVoucherReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VoucherHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VoucherHandler",
	HandlerType: (*VoucherHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserVoucher",
			Handler:    _VoucherHandler_GetUserVoucher_Handler,
		},
		{
			MethodName: "DrawVoucher",
			Handler:    _VoucherHandler_DrawVoucher_Handler,
		},
		{
			MethodName: "GetVoucherInfo",
			Handler:    _VoucherHandler_GetVoucherInfo_Handler,
		},
		{
			MethodName: "UseVoucher",
			Handler:    _VoucherHandler_UseVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voucher.proto",
}
