// Code generated by goctl. DO NOT EDIT!
// Source: advertisement.proto

package advertisementhandler

import (
	"context"

	"catering/proto/advertisement"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdBanner                       = proto.AdBanner
	AdHotActivitie                 = proto.AdHotActivitie
	AdRecommendDaily               = proto.AdRecommendDaily
	AdRecommendDailyProduct        = proto.AdRecommendDailyProduct
	GetAdBannerListReq             = proto.GetAdBannerListReq
	GetAdBannerListResp            = proto.GetAdBannerListResp
	GetAdHotActivitieReq           = proto.GetAdHotActivitieReq
	GetAdHotActivitieResp          = proto.GetAdHotActivitieResp
	GetAdRecommendDailyProductReq  = proto.GetAdRecommendDailyProductReq
	GetAdRecommendDailyProductResp = proto.GetAdRecommendDailyProductResp

	AdvertisementHandler interface {
		AdBannerList(ctx context.Context, in *GetAdBannerListReq, opts ...grpc.CallOption) (*GetAdBannerListResp, error)
		AdHotActivities(ctx context.Context, in *GetAdHotActivitieReq, opts ...grpc.CallOption) (*GetAdHotActivitieResp, error)
		AdRecommendDailyProducts(ctx context.Context, in *GetAdRecommendDailyProductReq, opts ...grpc.CallOption) (*GetAdRecommendDailyProductResp, error)
	}

	defaultAdvertisementHandler struct {
		cli zrpc.Client
	}
)

func NewAdvertisementHandler(cli zrpc.Client) AdvertisementHandler {
	return &defaultAdvertisementHandler{
		cli: cli,
	}
}

func (m *defaultAdvertisementHandler) AdBannerList(ctx context.Context, in *GetAdBannerListReq, opts ...grpc.CallOption) (*GetAdBannerListResp, error) {
	client := proto.NewAdvertisementHandlerClient(m.cli.Conn())
	return client.AdBannerList(ctx, in, opts...)
}

func (m *defaultAdvertisementHandler) AdHotActivities(ctx context.Context, in *GetAdHotActivitieReq, opts ...grpc.CallOption) (*GetAdHotActivitieResp, error) {
	client := proto.NewAdvertisementHandlerClient(m.cli.Conn())
	return client.AdHotActivities(ctx, in, opts...)
}

func (m *defaultAdvertisementHandler) AdRecommendDailyProducts(ctx context.Context, in *GetAdRecommendDailyProductReq, opts ...grpc.CallOption) (*GetAdRecommendDailyProductResp, error) {
	client := proto.NewAdvertisementHandlerClient(m.cli.Conn())
	return client.AdRecommendDailyProducts(ctx, in, opts...)
}
