// Code generated by goctl. DO NOT EDIT.
package types

type GetAdBannerListReq struct {
}

type GetAdBannerListResp struct {
}

type GetAdHotActivitieReq struct {
}

type GetAdHotActivitieResp struct {
}

type GetAdRecommendDailyProductReq struct {
}

type GetAdRecommendDailyProductResp struct {
}
