// Code generated by protoc-gen-go. DO NOT EDIT.
// source: advertisement.proto

package proto

import (
	product "catering/proto/product"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAdBannerListReq struct {
	BannerType           int32    `protobuf:"varint,1,opt,name=banner_type,json=bannerType,proto3" json:"banner_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdBannerListReq) Reset()         { *m = GetAdBannerListReq{} }
func (m *GetAdBannerListReq) String() string { return proto.CompactTextString(m) }
func (*GetAdBannerListReq) ProtoMessage()    {}
func (*GetAdBannerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{0}
}

func (m *GetAdBannerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdBannerListReq.Unmarshal(m, b)
}
func (m *GetAdBannerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdBannerListReq.Marshal(b, m, deterministic)
}
func (m *GetAdBannerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdBannerListReq.Merge(m, src)
}
func (m *GetAdBannerListReq) XXX_Size() int {
	return xxx_messageInfo_GetAdBannerListReq.Size(m)
}
func (m *GetAdBannerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdBannerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdBannerListReq proto.InternalMessageInfo

func (m *GetAdBannerListReq) GetBannerType() int32 {
	if m != nil {
		return m.BannerType
	}
	return 0
}

type GetAdBannerListResp struct {
	Banners              []*AdBanner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAdBannerListResp) Reset()         { *m = GetAdBannerListResp{} }
func (m *GetAdBannerListResp) String() string { return proto.CompactTextString(m) }
func (*GetAdBannerListResp) ProtoMessage()    {}
func (*GetAdBannerListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{1}
}

func (m *GetAdBannerListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdBannerListResp.Unmarshal(m, b)
}
func (m *GetAdBannerListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdBannerListResp.Marshal(b, m, deterministic)
}
func (m *GetAdBannerListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdBannerListResp.Merge(m, src)
}
func (m *GetAdBannerListResp) XXX_Size() int {
	return xxx_messageInfo_GetAdBannerListResp.Size(m)
}
func (m *GetAdBannerListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdBannerListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdBannerListResp proto.InternalMessageInfo

func (m *GetAdBannerListResp) GetBanners() []*AdBanner {
	if m != nil {
		return m.Banners
	}
	return nil
}

type GetAdHotActivitieReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdHotActivitieReq) Reset()         { *m = GetAdHotActivitieReq{} }
func (m *GetAdHotActivitieReq) String() string { return proto.CompactTextString(m) }
func (*GetAdHotActivitieReq) ProtoMessage()    {}
func (*GetAdHotActivitieReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{2}
}

func (m *GetAdHotActivitieReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdHotActivitieReq.Unmarshal(m, b)
}
func (m *GetAdHotActivitieReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdHotActivitieReq.Marshal(b, m, deterministic)
}
func (m *GetAdHotActivitieReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdHotActivitieReq.Merge(m, src)
}
func (m *GetAdHotActivitieReq) XXX_Size() int {
	return xxx_messageInfo_GetAdHotActivitieReq.Size(m)
}
func (m *GetAdHotActivitieReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdHotActivitieReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdHotActivitieReq proto.InternalMessageInfo

type GetAdHotActivitieResp struct {
	Activities           []*AdHotActivitie `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAdHotActivitieResp) Reset()         { *m = GetAdHotActivitieResp{} }
func (m *GetAdHotActivitieResp) String() string { return proto.CompactTextString(m) }
func (*GetAdHotActivitieResp) ProtoMessage()    {}
func (*GetAdHotActivitieResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{3}
}

func (m *GetAdHotActivitieResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdHotActivitieResp.Unmarshal(m, b)
}
func (m *GetAdHotActivitieResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdHotActivitieResp.Marshal(b, m, deterministic)
}
func (m *GetAdHotActivitieResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdHotActivitieResp.Merge(m, src)
}
func (m *GetAdHotActivitieResp) XXX_Size() int {
	return xxx_messageInfo_GetAdHotActivitieResp.Size(m)
}
func (m *GetAdHotActivitieResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdHotActivitieResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdHotActivitieResp proto.InternalMessageInfo

func (m *GetAdHotActivitieResp) GetActivities() []*AdHotActivitie {
	if m != nil {
		return m.Activities
	}
	return nil
}

type GetAdRecommendDailyProductReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdRecommendDailyProductReq) Reset()         { *m = GetAdRecommendDailyProductReq{} }
func (m *GetAdRecommendDailyProductReq) String() string { return proto.CompactTextString(m) }
func (*GetAdRecommendDailyProductReq) ProtoMessage()    {}
func (*GetAdRecommendDailyProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{4}
}

func (m *GetAdRecommendDailyProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdRecommendDailyProductReq.Unmarshal(m, b)
}
func (m *GetAdRecommendDailyProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdRecommendDailyProductReq.Marshal(b, m, deterministic)
}
func (m *GetAdRecommendDailyProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdRecommendDailyProductReq.Merge(m, src)
}
func (m *GetAdRecommendDailyProductReq) XXX_Size() int {
	return xxx_messageInfo_GetAdRecommendDailyProductReq.Size(m)
}
func (m *GetAdRecommendDailyProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdRecommendDailyProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdRecommendDailyProductReq proto.InternalMessageInfo

type GetAdRecommendDailyProductResp struct {
	Dailys               []*AdRecommendDailyProduct `protobuf:"bytes,1,rep,name=dailys,proto3" json:"dailys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetAdRecommendDailyProductResp) Reset()         { *m = GetAdRecommendDailyProductResp{} }
func (m *GetAdRecommendDailyProductResp) String() string { return proto.CompactTextString(m) }
func (*GetAdRecommendDailyProductResp) ProtoMessage()    {}
func (*GetAdRecommendDailyProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{5}
}

func (m *GetAdRecommendDailyProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdRecommendDailyProductResp.Unmarshal(m, b)
}
func (m *GetAdRecommendDailyProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdRecommendDailyProductResp.Marshal(b, m, deterministic)
}
func (m *GetAdRecommendDailyProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdRecommendDailyProductResp.Merge(m, src)
}
func (m *GetAdRecommendDailyProductResp) XXX_Size() int {
	return xxx_messageInfo_GetAdRecommendDailyProductResp.Size(m)
}
func (m *GetAdRecommendDailyProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdRecommendDailyProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdRecommendDailyProductResp proto.InternalMessageInfo

func (m *GetAdRecommendDailyProductResp) GetDailys() []*AdRecommendDailyProduct {
	if m != nil {
		return m.Dailys
	}
	return nil
}

type AdBanner struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BannerType           int32    `protobuf:"varint,2,opt,name=banner_type,json=bannerType,proto3" json:"banner_type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PicUrl               string   `protobuf:"bytes,4,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Sort                 int32    `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	BeginTime            string   `protobuf:"bytes,8,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime              string   `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedTime          int64    `protobuf:"varint,10,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,11,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdBanner) Reset()         { *m = AdBanner{} }
func (m *AdBanner) String() string { return proto.CompactTextString(m) }
func (*AdBanner) ProtoMessage()    {}
func (*AdBanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{6}
}

func (m *AdBanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdBanner.Unmarshal(m, b)
}
func (m *AdBanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdBanner.Marshal(b, m, deterministic)
}
func (m *AdBanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdBanner.Merge(m, src)
}
func (m *AdBanner) XXX_Size() int {
	return xxx_messageInfo_AdBanner.Size(m)
}
func (m *AdBanner) XXX_DiscardUnknown() {
	xxx_messageInfo_AdBanner.DiscardUnknown(m)
}

var xxx_messageInfo_AdBanner proto.InternalMessageInfo

func (m *AdBanner) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdBanner) GetBannerType() int32 {
	if m != nil {
		return m.BannerType
	}
	return 0
}

func (m *AdBanner) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdBanner) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *AdBanner) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdBanner) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdBanner) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdBanner) GetBeginTime() string {
	if m != nil {
		return m.BeginTime
	}
	return ""
}

func (m *AdBanner) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *AdBanner) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *AdBanner) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

type AdHotActivitie struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivatieName        string   `protobuf:"bytes,2,opt,name=activatie_name,json=activatieName,proto3" json:"activatie_name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle             string   `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Sort                 int32    `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	PicUrl               string   `protobuf:"bytes,8,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	BeginTime            string   `protobuf:"bytes,9,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime              string   `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedTime          int64    `protobuf:"varint,11,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,12,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdHotActivitie) Reset()         { *m = AdHotActivitie{} }
func (m *AdHotActivitie) String() string { return proto.CompactTextString(m) }
func (*AdHotActivitie) ProtoMessage()    {}
func (*AdHotActivitie) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{7}
}

func (m *AdHotActivitie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdHotActivitie.Unmarshal(m, b)
}
func (m *AdHotActivitie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdHotActivitie.Marshal(b, m, deterministic)
}
func (m *AdHotActivitie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdHotActivitie.Merge(m, src)
}
func (m *AdHotActivitie) XXX_Size() int {
	return xxx_messageInfo_AdHotActivitie.Size(m)
}
func (m *AdHotActivitie) XXX_DiscardUnknown() {
	xxx_messageInfo_AdHotActivitie.DiscardUnknown(m)
}

var xxx_messageInfo_AdHotActivitie proto.InternalMessageInfo

func (m *AdHotActivitie) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdHotActivitie) GetActivatieName() string {
	if m != nil {
		return m.ActivatieName
	}
	return ""
}

func (m *AdHotActivitie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdHotActivitie) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *AdHotActivitie) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AdHotActivitie) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdHotActivitie) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdHotActivitie) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *AdHotActivitie) GetBeginTime() string {
	if m != nil {
		return m.BeginTime
	}
	return ""
}

func (m *AdHotActivitie) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *AdHotActivitie) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *AdHotActivitie) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

type AdRecommendDailyProduct struct {
	Ad                   *AdRecommendDaily    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	Product              *product.ProductBase `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AdRecommendDailyProduct) Reset()         { *m = AdRecommendDailyProduct{} }
func (m *AdRecommendDailyProduct) String() string { return proto.CompactTextString(m) }
func (*AdRecommendDailyProduct) ProtoMessage()    {}
func (*AdRecommendDailyProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{8}
}

func (m *AdRecommendDailyProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdRecommendDailyProduct.Unmarshal(m, b)
}
func (m *AdRecommendDailyProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdRecommendDailyProduct.Marshal(b, m, deterministic)
}
func (m *AdRecommendDailyProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdRecommendDailyProduct.Merge(m, src)
}
func (m *AdRecommendDailyProduct) XXX_Size() int {
	return xxx_messageInfo_AdRecommendDailyProduct.Size(m)
}
func (m *AdRecommendDailyProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_AdRecommendDailyProduct.DiscardUnknown(m)
}

var xxx_messageInfo_AdRecommendDailyProduct proto.InternalMessageInfo

func (m *AdRecommendDailyProduct) GetAd() *AdRecommendDaily {
	if m != nil {
		return m.Ad
	}
	return nil
}

func (m *AdRecommendDailyProduct) GetProduct() *product.ProductBase {
	if m != nil {
		return m.Product
	}
	return nil
}

type AdRecommendDaily struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            int64    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle             string   `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	PicUrl               string   `protobuf:"bytes,6,opt,name=pic_url,json=picUrl,proto3" json:"pic_url,omitempty"`
	Sort                 int32    `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	BeginTime            string   `protobuf:"bytes,9,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime              string   `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedTime          int64    `protobuf:"varint,11,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,12,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdRecommendDaily) Reset()         { *m = AdRecommendDaily{} }
func (m *AdRecommendDaily) String() string { return proto.CompactTextString(m) }
func (*AdRecommendDaily) ProtoMessage()    {}
func (*AdRecommendDaily) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d029e37b0aceb, []int{9}
}

func (m *AdRecommendDaily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdRecommendDaily.Unmarshal(m, b)
}
func (m *AdRecommendDaily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdRecommendDaily.Marshal(b, m, deterministic)
}
func (m *AdRecommendDaily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdRecommendDaily.Merge(m, src)
}
func (m *AdRecommendDaily) XXX_Size() int {
	return xxx_messageInfo_AdRecommendDaily.Size(m)
}
func (m *AdRecommendDaily) XXX_DiscardUnknown() {
	xxx_messageInfo_AdRecommendDaily.DiscardUnknown(m)
}

var xxx_messageInfo_AdRecommendDaily proto.InternalMessageInfo

func (m *AdRecommendDaily) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdRecommendDaily) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *AdRecommendDaily) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdRecommendDaily) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *AdRecommendDaily) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AdRecommendDaily) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *AdRecommendDaily) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdRecommendDaily) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdRecommendDaily) GetBeginTime() string {
	if m != nil {
		return m.BeginTime
	}
	return ""
}

func (m *AdRecommendDaily) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *AdRecommendDaily) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *AdRecommendDaily) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAdBannerListReq)(nil), "proto.GetAdBannerListReq")
	proto.RegisterType((*GetAdBannerListResp)(nil), "proto.GetAdBannerListResp")
	proto.RegisterType((*GetAdHotActivitieReq)(nil), "proto.GetAdHotActivitieReq")
	proto.RegisterType((*GetAdHotActivitieResp)(nil), "proto.GetAdHotActivitieResp")
	proto.RegisterType((*GetAdRecommendDailyProductReq)(nil), "proto.GetAdRecommendDailyProductReq")
	proto.RegisterType((*GetAdRecommendDailyProductResp)(nil), "proto.GetAdRecommendDailyProductResp")
	proto.RegisterType((*AdBanner)(nil), "proto.AdBanner")
	proto.RegisterType((*AdHotActivitie)(nil), "proto.AdHotActivitie")
	proto.RegisterType((*AdRecommendDailyProduct)(nil), "proto.AdRecommendDailyProduct")
	proto.RegisterType((*AdRecommendDaily)(nil), "proto.AdRecommendDaily")
}

func init() { proto.RegisterFile("advertisement.proto", fileDescriptor_b91d029e37b0aceb) }

var fileDescriptor_b91d029e37b0aceb = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0xc5, 0x72, 0xfc, 0x37, 0xca, 0x97, 0x7c, 0x4c, 0xfe, 0x14, 0xb7, 0xf9, 0xa9, 0x68, 0x68,
	0x0a, 0x25, 0x05, 0x97, 0xf4, 0xba, 0x09, 0x2d, 0x4d, 0x21, 0x84, 0x22, 0x52, 0xe8, 0x9d, 0x59,
	0x6b, 0x87, 0xb0, 0xd4, 0x92, 0x36, 0xda, 0x75, 0x20, 0xef, 0xd1, 0xe7, 0xe8, 0xc3, 0xf4, 0xaa,
	0x8f, 0x53, 0xbc, 0xbb, 0x72, 0x24, 0x3b, 0x4a, 0x5b, 0x28, 0xf4, 0x4a, 0x9e, 0x33, 0x67, 0xcf,
	0xb0, 0xe7, 0xac, 0x07, 0xd6, 0x18, 0xbf, 0xa1, 0x5c, 0x0b, 0x45, 0x09, 0xa5, 0xfa, 0x48, 0xe6,
	0x99, 0xce, 0xb0, 0x65, 0x3e, 0xfd, 0x0d, 0x99, 0x67, 0x7c, 0x12, 0xeb, 0x97, 0xee, 0x6b, 0xbb,
	0xe1, 0x31, 0xe0, 0x7b, 0xd2, 0x27, 0xfc, 0x94, 0xa5, 0x29, 0xe5, 0xe7, 0x42, 0xe9, 0x88, 0xae,
	0x71, 0x0f, 0xfc, 0x91, 0x01, 0x86, 0xfa, 0x56, 0x52, 0xd0, 0xd8, 0x6f, 0x1c, 0xb6, 0x22, 0xb0,
	0xd0, 0xe5, 0xad, 0xa4, 0xf0, 0x0d, 0xac, 0x2d, 0x1c, 0x53, 0x12, 0x9f, 0x43, 0xc7, 0x92, 0x54,
	0xd0, 0xd8, 0x6f, 0x1e, 0xfa, 0x83, 0x55, 0x3b, 0xe6, 0xa8, 0x60, 0x46, 0x45, 0x3f, 0xdc, 0x84,
	0x75, 0xa3, 0x70, 0x96, 0xe9, 0x93, 0x58, 0x8b, 0x1b, 0xa1, 0x05, 0x45, 0x74, 0x1d, 0x5e, 0xc0,
	0xc6, 0x3d, 0xb8, 0x92, 0x78, 0x0c, 0xc0, 0x0a, 0xa0, 0x90, 0xdf, 0x98, 0xc9, 0x57, 0xe8, 0x25,
	0x62, 0xb8, 0x07, 0x3b, 0x46, 0x2f, 0xa2, 0x38, 0x4b, 0x12, 0x4a, 0xf9, 0x5b, 0x26, 0xc6, 0xb7,
	0x1f, 0xad, 0x09, 0xd3, 0x81, 0x9f, 0x61, 0xf7, 0x21, 0x82, 0x92, 0xf8, 0x1a, 0xda, 0x7c, 0x8a,
	0x15, 0x53, 0x77, 0x67, 0x53, 0xef, 0x3f, 0xe3, 0xd8, 0xe1, 0x37, 0x0f, 0xba, 0xc5, 0xc5, 0x71,
	0x05, 0x3c, 0xc1, 0x8d, 0x93, 0xcd, 0xc8, 0x13, 0x7c, 0xde, 0x62, 0x6f, 0xde, 0x62, 0x5c, 0x87,
	0x96, 0x16, 0x7a, 0x4c, 0x41, 0x73, 0xbf, 0x71, 0xd8, 0x8b, 0x6c, 0x81, 0x5b, 0xd0, 0x91, 0x22,
	0x1e, 0x4e, 0xf2, 0x71, 0xb0, 0x64, 0xf0, 0xb6, 0x14, 0xf1, 0xa7, 0x7c, 0x8c, 0x9b, 0xd0, 0xce,
	0x29, 0x61, 0xf9, 0x97, 0xa0, 0x65, 0x71, 0x5b, 0x4d, 0x71, 0xa5, 0x99, 0x9e, 0xa8, 0xa0, 0x6d,
	0x46, 0xb8, 0x0a, 0x11, 0x96, 0x54, 0x96, 0xeb, 0xa0, 0x63, 0x50, 0xf3, 0x1b, 0x77, 0x00, 0x46,
	0x74, 0x25, 0xd2, 0xa1, 0x16, 0x09, 0x05, 0x5d, 0xa3, 0xd3, 0x33, 0xc8, 0xa5, 0x48, 0x08, 0xb7,
	0xa1, 0x4b, 0x29, 0xb7, 0xcd, 0x9e, 0x69, 0x76, 0x28, 0xe5, 0xa6, 0xf5, 0x04, 0x96, 0xe3, 0x9c,
	0x98, 0x26, 0xd7, 0x06, 0x73, 0x4f, 0xdf, 0x61, 0x05, 0x65, 0x22, 0xf9, 0x1d, 0xc5, 0x37, 0x0a,
	0xbe, 0xc3, 0xa6, 0x94, 0xf0, 0x87, 0x07, 0x2b, 0xd5, 0x28, 0x17, 0x6c, 0x3b, 0x80, 0x15, 0x13,
	0x2e, 0xd3, 0x82, 0x86, 0x29, 0x4b, 0xac, 0x73, 0xbd, 0xe8, 0xbf, 0x19, 0x7a, 0xc1, 0x92, 0x3a,
	0xf3, 0xfa, 0xd0, 0x55, 0x93, 0x91, 0x6d, 0x58, 0xf7, 0x66, 0x35, 0x06, 0xd0, 0x89, 0xb3, 0x54,
	0x53, 0xaa, 0x9d, 0x81, 0x45, 0xf9, 0x47, 0x0e, 0x96, 0xe2, 0xe9, 0x56, 0xe2, 0xa9, 0x5a, 0xdb,
	0x7b, 0xc8, 0x5a, 0x78, 0xd8, 0x5a, 0xff, 0xd7, 0xd6, 0x2e, 0x2f, 0x5a, 0x2b, 0x61, 0xab, 0xe6,
	0xb9, 0xe2, 0x33, 0xf0, 0x98, 0xb5, 0xd8, 0x1f, 0x6c, 0xd5, 0x3c, 0xed, 0xc8, 0x63, 0x1c, 0x5f,
	0x40, 0xc7, 0x2d, 0x0f, 0x63, 0xba, 0x3f, 0x40, 0xc7, 0x76, 0x4a, 0xa7, 0x4c, 0x51, 0x54, 0x50,
	0xc2, 0xef, 0x1e, 0xfc, 0x3f, 0x2f, 0xb3, 0x10, 0xe7, 0x0e, 0x80, 0xe3, 0x0f, 0x05, 0x37, 0xaa,
	0xcd, 0xa8, 0xe7, 0x90, 0x0f, 0xfc, 0xaf, 0xc6, 0x58, 0x8a, 0xa6, 0x5d, 0x89, 0xe6, 0xbe, 0x1c,
	0xef, 0x32, 0xef, 0x56, 0x32, 0xff, 0xc7, 0x31, 0x0e, 0xbe, 0x7a, 0xb0, 0x7e, 0x52, 0x5e, 0xf2,
	0x67, 0x2c, 0xe5, 0x63, 0xca, 0xf1, 0x1d, 0x2c, 0x97, 0xb7, 0x31, 0x6e, 0xbb, 0x68, 0x16, 0x97,
	0x7b, 0xbf, 0x5f, 0xd7, 0x52, 0x12, 0xcf, 0x61, 0xb5, 0xfa, 0x07, 0x54, 0xf8, 0xa8, 0x4c, 0x9f,
	0xdb, 0xd6, 0xfd, 0xc7, 0xf5, 0x4d, 0x25, 0xf1, 0x0a, 0x82, 0x9a, 0x47, 0xa7, 0xf0, 0x69, 0xf9,
	0x64, 0xdd, 0x72, 0xee, 0x1f, 0xfc, 0x06, 0x4b, 0xc9, 0x51, 0xdb, 0xb0, 0x5e, 0xfd, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0x5d, 0x1d, 0x82, 0x01, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdvertisementHandlerClient is the client API for AdvertisementHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdvertisementHandlerClient interface {
	AdBannerList(ctx context.Context, in *GetAdBannerListReq, opts ...grpc.CallOption) (*GetAdBannerListResp, error)
	AdHotActivities(ctx context.Context, in *GetAdHotActivitieReq, opts ...grpc.CallOption) (*GetAdHotActivitieResp, error)
	AdRecommendDailyProducts(ctx context.Context, in *GetAdRecommendDailyProductReq, opts ...grpc.CallOption) (*GetAdRecommendDailyProductResp, error)
}

type advertisementHandlerClient struct {
	cc *grpc.ClientConn
}

func NewAdvertisementHandlerClient(cc *grpc.ClientConn) AdvertisementHandlerClient {
	return &advertisementHandlerClient{cc}
}

func (c *advertisementHandlerClient) AdBannerList(ctx context.Context, in *GetAdBannerListReq, opts ...grpc.CallOption) (*GetAdBannerListResp, error) {
	out := new(GetAdBannerListResp)
	err := c.cc.Invoke(ctx, "/proto.AdvertisementHandler/AdBannerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementHandlerClient) AdHotActivities(ctx context.Context, in *GetAdHotActivitieReq, opts ...grpc.CallOption) (*GetAdHotActivitieResp, error) {
	out := new(GetAdHotActivitieResp)
	err := c.cc.Invoke(ctx, "/proto.AdvertisementHandler/AdHotActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementHandlerClient) AdRecommendDailyProducts(ctx context.Context, in *GetAdRecommendDailyProductReq, opts ...grpc.CallOption) (*GetAdRecommendDailyProductResp, error) {
	out := new(GetAdRecommendDailyProductResp)
	err := c.cc.Invoke(ctx, "/proto.AdvertisementHandler/AdRecommendDailyProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvertisementHandlerServer is the server API for AdvertisementHandler service.
type AdvertisementHandlerServer interface {
	AdBannerList(context.Context, *GetAdBannerListReq) (*GetAdBannerListResp, error)
	AdHotActivities(context.Context, *GetAdHotActivitieReq) (*GetAdHotActivitieResp, error)
	AdRecommendDailyProducts(context.Context, *GetAdRecommendDailyProductReq) (*GetAdRecommendDailyProductResp, error)
}

// UnimplementedAdvertisementHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedAdvertisementHandlerServer struct {
}

func (*UnimplementedAdvertisementHandlerServer) AdBannerList(ctx context.Context, req *GetAdBannerListReq) (*GetAdBannerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdBannerList not implemented")
}
func (*UnimplementedAdvertisementHandlerServer) AdHotActivities(ctx context.Context, req *GetAdHotActivitieReq) (*GetAdHotActivitieResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdHotActivities not implemented")
}
func (*UnimplementedAdvertisementHandlerServer) AdRecommendDailyProducts(ctx context.Context, req *GetAdRecommendDailyProductReq) (*GetAdRecommendDailyProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdRecommendDailyProducts not implemented")
}

func RegisterAdvertisementHandlerServer(s *grpc.Server, srv AdvertisementHandlerServer) {
	s.RegisterService(&_AdvertisementHandler_serviceDesc, srv)
}

func _AdvertisementHandler_AdBannerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdBannerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementHandlerServer).AdBannerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdvertisementHandler/AdBannerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementHandlerServer).AdBannerList(ctx, req.(*GetAdBannerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementHandler_AdHotActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdHotActivitieReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementHandlerServer).AdHotActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdvertisementHandler/AdHotActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementHandlerServer).AdHotActivities(ctx, req.(*GetAdHotActivitieReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementHandler_AdRecommendDailyProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdRecommendDailyProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementHandlerServer).AdRecommendDailyProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdvertisementHandler/AdRecommendDailyProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementHandlerServer).AdRecommendDailyProducts(ctx, req.(*GetAdRecommendDailyProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdvertisementHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AdvertisementHandler",
	HandlerType: (*AdvertisementHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdBannerList",
			Handler:    _AdvertisementHandler_AdBannerList_Handler,
		},
		{
			MethodName: "AdHotActivities",
			Handler:    _AdvertisementHandler_AdHotActivities_Handler,
		},
		{
			MethodName: "AdRecommendDailyProducts",
			Handler:    _AdvertisementHandler_AdRecommendDailyProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advertisement.proto",
}
