// Code generated by protoc-gen-go. DO NOT EDIT.
// source: area.proto

package common

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProvincesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProvincesReq) Reset()         { *m = GetProvincesReq{} }
func (m *GetProvincesReq) String() string { return proto.CompactTextString(m) }
func (*GetProvincesReq) ProtoMessage()    {}
func (*GetProvincesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *GetProvincesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvincesReq.Unmarshal(m, b)
}
func (m *GetProvincesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvincesReq.Marshal(b, m, deterministic)
}
func (m *GetProvincesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvincesReq.Merge(m, src)
}
func (m *GetProvincesReq) XXX_Size() int {
	return xxx_messageInfo_GetProvincesReq.Size(m)
}
func (m *GetProvincesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvincesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvincesReq proto.InternalMessageInfo

type GetProvincesResp struct {
	Provinces            []*Province `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetProvincesResp) Reset()         { *m = GetProvincesResp{} }
func (m *GetProvincesResp) String() string { return proto.CompactTextString(m) }
func (*GetProvincesResp) ProtoMessage()    {}
func (*GetProvincesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *GetProvincesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvincesResp.Unmarshal(m, b)
}
func (m *GetProvincesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvincesResp.Marshal(b, m, deterministic)
}
func (m *GetProvincesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvincesResp.Merge(m, src)
}
func (m *GetProvincesResp) XXX_Size() int {
	return xxx_messageInfo_GetProvincesResp.Size(m)
}
func (m *GetProvincesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvincesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvincesResp proto.InternalMessageInfo

func (m *GetProvincesResp) GetProvinces() []*Province {
	if m != nil {
		return m.Provinces
	}
	return nil
}

type GetCitysReq struct {
	ProvinceId           int64    `protobuf:"varint,1,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCitysReq) Reset()         { *m = GetCitysReq{} }
func (m *GetCitysReq) String() string { return proto.CompactTextString(m) }
func (*GetCitysReq) ProtoMessage()    {}
func (*GetCitysReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *GetCitysReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitysReq.Unmarshal(m, b)
}
func (m *GetCitysReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitysReq.Marshal(b, m, deterministic)
}
func (m *GetCitysReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitysReq.Merge(m, src)
}
func (m *GetCitysReq) XXX_Size() int {
	return xxx_messageInfo_GetCitysReq.Size(m)
}
func (m *GetCitysReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitysReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitysReq proto.InternalMessageInfo

func (m *GetCitysReq) GetProvinceId() int64 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

type GetCitysResp struct {
	Citys                []*City  `protobuf:"bytes,1,rep,name=citys,proto3" json:"citys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCitysResp) Reset()         { *m = GetCitysResp{} }
func (m *GetCitysResp) String() string { return proto.CompactTextString(m) }
func (*GetCitysResp) ProtoMessage()    {}
func (*GetCitysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *GetCitysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitysResp.Unmarshal(m, b)
}
func (m *GetCitysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitysResp.Marshal(b, m, deterministic)
}
func (m *GetCitysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitysResp.Merge(m, src)
}
func (m *GetCitysResp) XXX_Size() int {
	return xxx_messageInfo_GetCitysResp.Size(m)
}
func (m *GetCitysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitysResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitysResp proto.InternalMessageInfo

func (m *GetCitysResp) GetCitys() []*City {
	if m != nil {
		return m.Citys
	}
	return nil
}

type GetDistinctsReq struct {
	CityId               int64    `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDistinctsReq) Reset()         { *m = GetDistinctsReq{} }
func (m *GetDistinctsReq) String() string { return proto.CompactTextString(m) }
func (*GetDistinctsReq) ProtoMessage()    {}
func (*GetDistinctsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *GetDistinctsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDistinctsReq.Unmarshal(m, b)
}
func (m *GetDistinctsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDistinctsReq.Marshal(b, m, deterministic)
}
func (m *GetDistinctsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDistinctsReq.Merge(m, src)
}
func (m *GetDistinctsReq) XXX_Size() int {
	return xxx_messageInfo_GetDistinctsReq.Size(m)
}
func (m *GetDistinctsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDistinctsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDistinctsReq proto.InternalMessageInfo

func (m *GetDistinctsReq) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type GetDistinctsResp struct {
	Distincts            []*Distinct `protobuf:"bytes,1,rep,name=distincts,proto3" json:"distincts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDistinctsResp) Reset()         { *m = GetDistinctsResp{} }
func (m *GetDistinctsResp) String() string { return proto.CompactTextString(m) }
func (*GetDistinctsResp) ProtoMessage()    {}
func (*GetDistinctsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *GetDistinctsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDistinctsResp.Unmarshal(m, b)
}
func (m *GetDistinctsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDistinctsResp.Marshal(b, m, deterministic)
}
func (m *GetDistinctsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDistinctsResp.Merge(m, src)
}
func (m *GetDistinctsResp) XXX_Size() int {
	return xxx_messageInfo_GetDistinctsResp.Size(m)
}
func (m *GetDistinctsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDistinctsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDistinctsResp proto.InternalMessageInfo

func (m *GetDistinctsResp) GetDistincts() []*Distinct {
	if m != nil {
		return m.Distincts
	}
	return nil
}

type GetProvincesDetailReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProvincesDetailReq) Reset()         { *m = GetProvincesDetailReq{} }
func (m *GetProvincesDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetProvincesDetailReq) ProtoMessage()    {}
func (*GetProvincesDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *GetProvincesDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvincesDetailReq.Unmarshal(m, b)
}
func (m *GetProvincesDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvincesDetailReq.Marshal(b, m, deterministic)
}
func (m *GetProvincesDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvincesDetailReq.Merge(m, src)
}
func (m *GetProvincesDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetProvincesDetailReq.Size(m)
}
func (m *GetProvincesDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvincesDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvincesDetailReq proto.InternalMessageInfo

type GetProvincesDetailResp struct {
	Provinces            []*Province `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetProvincesDetailResp) Reset()         { *m = GetProvincesDetailResp{} }
func (m *GetProvincesDetailResp) String() string { return proto.CompactTextString(m) }
func (*GetProvincesDetailResp) ProtoMessage()    {}
func (*GetProvincesDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *GetProvincesDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProvincesDetailResp.Unmarshal(m, b)
}
func (m *GetProvincesDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProvincesDetailResp.Marshal(b, m, deterministic)
}
func (m *GetProvincesDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProvincesDetailResp.Merge(m, src)
}
func (m *GetProvincesDetailResp) XXX_Size() int {
	return xxx_messageInfo_GetProvincesDetailResp.Size(m)
}
func (m *GetProvincesDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProvincesDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProvincesDetailResp proto.InternalMessageInfo

func (m *GetProvincesDetailResp) GetProvinces() []*Province {
	if m != nil {
		return m.Provinces
	}
	return nil
}

type Province struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvinceName         string   `protobuf:"bytes,2,opt,name=provinceName,proto3" json:"provinceName,omitempty"`
	Citys                []*City  `protobuf:"bytes,3,rep,name=citys,proto3" json:"citys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Province) Reset()         { *m = Province{} }
func (m *Province) String() string { return proto.CompactTextString(m) }
func (*Province) ProtoMessage()    {}
func (*Province) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *Province) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Province.Unmarshal(m, b)
}
func (m *Province) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Province.Marshal(b, m, deterministic)
}
func (m *Province) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Province.Merge(m, src)
}
func (m *Province) XXX_Size() int {
	return xxx_messageInfo_Province.Size(m)
}
func (m *Province) XXX_DiscardUnknown() {
	xxx_messageInfo_Province.DiscardUnknown(m)
}

var xxx_messageInfo_Province proto.InternalMessageInfo

func (m *Province) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Province) GetProvinceName() string {
	if m != nil {
		return m.ProvinceName
	}
	return ""
}

func (m *Province) GetCitys() []*City {
	if m != nil {
		return m.Citys
	}
	return nil
}

type City struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CityName             string      `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	Distincts            []*Distinct `protobuf:"bytes,3,rep,name=distincts,proto3" json:"distincts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *City) GetDistincts() []*Distinct {
	if m != nil {
		return m.Distincts
	}
	return nil
}

type Distinct struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DistinctName         string   `protobuf:"bytes,2,opt,name=distinctName,proto3" json:"distinctName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distinct) Reset()         { *m = Distinct{} }
func (m *Distinct) String() string { return proto.CompactTextString(m) }
func (*Distinct) ProtoMessage()    {}
func (*Distinct) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *Distinct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distinct.Unmarshal(m, b)
}
func (m *Distinct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distinct.Marshal(b, m, deterministic)
}
func (m *Distinct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distinct.Merge(m, src)
}
func (m *Distinct) XXX_Size() int {
	return xxx_messageInfo_Distinct.Size(m)
}
func (m *Distinct) XXX_DiscardUnknown() {
	xxx_messageInfo_Distinct.DiscardUnknown(m)
}

var xxx_messageInfo_Distinct proto.InternalMessageInfo

func (m *Distinct) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Distinct) GetDistinctName() string {
	if m != nil {
		return m.DistinctName
	}
	return ""
}

type OrderByOptions struct {
	Options              []*OrderByOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderByOptions) Reset()         { *m = OrderByOptions{} }
func (m *OrderByOptions) String() string { return proto.CompactTextString(m) }
func (*OrderByOptions) ProtoMessage()    {}
func (*OrderByOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *OrderByOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderByOptions.Unmarshal(m, b)
}
func (m *OrderByOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderByOptions.Marshal(b, m, deterministic)
}
func (m *OrderByOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderByOptions.Merge(m, src)
}
func (m *OrderByOptions) XXX_Size() int {
	return xxx_messageInfo_OrderByOptions.Size(m)
}
func (m *OrderByOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderByOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OrderByOptions proto.InternalMessageInfo

func (m *OrderByOptions) GetOptions() []*OrderByOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type OrderByOption struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Desc                 int32    `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderByOption) Reset()         { *m = OrderByOption{} }
func (m *OrderByOption) String() string { return proto.CompactTextString(m) }
func (*OrderByOption) ProtoMessage()    {}
func (*OrderByOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *OrderByOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderByOption.Unmarshal(m, b)
}
func (m *OrderByOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderByOption.Marshal(b, m, deterministic)
}
func (m *OrderByOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderByOption.Merge(m, src)
}
func (m *OrderByOption) XXX_Size() int {
	return xxx_messageInfo_OrderByOption.Size(m)
}
func (m *OrderByOption) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderByOption.DiscardUnknown(m)
}

var xxx_messageInfo_OrderByOption proto.InternalMessageInfo

func (m *OrderByOption) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *OrderByOption) GetDesc() int32 {
	if m != nil {
		return m.Desc
	}
	return 0
}

func init() {
	proto.RegisterType((*GetProvincesReq)(nil), "area.GetProvincesReq")
	proto.RegisterType((*GetProvincesResp)(nil), "area.GetProvincesResp")
	proto.RegisterType((*GetCitysReq)(nil), "area.GetCitysReq")
	proto.RegisterType((*GetCitysResp)(nil), "area.GetCitysResp")
	proto.RegisterType((*GetDistinctsReq)(nil), "area.GetDistinctsReq")
	proto.RegisterType((*GetDistinctsResp)(nil), "area.GetDistinctsResp")
	proto.RegisterType((*GetProvincesDetailReq)(nil), "area.GetProvincesDetailReq")
	proto.RegisterType((*GetProvincesDetailResp)(nil), "area.GetProvincesDetailResp")
	proto.RegisterType((*Province)(nil), "area.Province")
	proto.RegisterType((*City)(nil), "area.City")
	proto.RegisterType((*Distinct)(nil), "area.Distinct")
	proto.RegisterType((*OrderByOptions)(nil), "area.OrderByOptions")
	proto.RegisterType((*OrderByOption)(nil), "area.OrderByOption")
}

func init() { proto.RegisterFile("area.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0x92, 0x36, 0x4d, 0x26, 0x6e, 0x29, 0x03, 0x6d, 0x2c, 0x4b, 0x40, 0xb4, 0xa7, 0x88,
	0x83, 0x91, 0xc2, 0x81, 0x03, 0x12, 0x12, 0x4d, 0xa5, 0xb6, 0x17, 0x8a, 0x56, 0xe2, 0x8c, 0x12,
	0xef, 0x1e, 0x56, 0x8a, 0xbd, 0xc6, 0x5e, 0x90, 0xfa, 0x49, 0xfc, 0x25, 0xda, 0xb5, 0xc7, 0xf6,
	0x26, 0x06, 0xa4, 0xde, 0x76, 0xde, 0x7b, 0x99, 0xb7, 0xf3, 0x32, 0x6b, 0x08, 0x12, 0x9d, 0xa6,
	0x3a, 0x8b, 0xf3, 0x42, 0x1b, 0x8d, 0xe3, 0xaa, 0x62, 0xcf, 0xe1, 0xd9, 0xad, 0x34, 0x5f, 0x0b,
	0xfd, 0x4b, 0x65, 0x89, 0x2c, 0xb9, 0xfc, 0xc1, 0xae, 0xe1, 0xc2, 0x87, 0xca, 0x1c, 0x63, 0x98,
	0xe6, 0x04, 0x84, 0x83, 0xc5, 0x68, 0x39, 0x5b, 0x5d, 0xc4, 0x75, 0x43, 0x52, 0xf2, 0x56, 0xc2,
	0x62, 0x98, 0xdd, 0x4a, 0xb3, 0x56, 0xe6, 0xd1, 0xb6, 0xc4, 0x37, 0x30, 0x23, 0xee, 0xbb, 0x12,
	0xe1, 0x60, 0x31, 0x58, 0x8e, 0x38, 0x10, 0x74, 0x2f, 0xd8, 0x0a, 0x82, 0x56, 0x5f, 0xe6, 0xc8,
	0xe0, 0x24, 0xb1, 0x45, 0xed, 0x15, 0x90, 0x97, 0x55, 0xf0, 0x8a, 0x62, 0x6f, 0xdd, 0xd5, 0x6f,
	0x54, 0x69, 0x54, 0x96, 0x18, 0xe7, 0x33, 0x87, 0x53, 0xcb, 0xb5, 0x1e, 0x63, 0x5b, 0xde, 0x8b,
	0x7a, 0xa6, 0x8e, 0xb6, 0x9a, 0x49, 0x10, 0xb0, 0x3f, 0x13, 0x29, 0x79, 0x2b, 0x61, 0x73, 0xb8,
	0xec, 0xe6, 0x72, 0x23, 0xcd, 0x46, 0xed, 0x6c, 0x60, 0x77, 0x70, 0xd5, 0x47, 0x3c, 0x21, 0xb6,
	0x2d, 0x4c, 0x08, 0xc6, 0x73, 0x18, 0x36, 0x63, 0x0c, 0x95, 0x40, 0x06, 0x01, 0x09, 0xbf, 0x6c,
	0x52, 0x19, 0x0e, 0x17, 0x83, 0xe5, 0x94, 0x7b, 0x58, 0x1b, 0xdb, 0xe8, 0xef, 0xb1, 0x6d, 0xe1,
	0xd8, 0x96, 0x07, 0xfd, 0x23, 0x98, 0x58, 0x41, 0xa7, 0x77, 0x53, 0xfb, 0x51, 0x8d, 0xfe, 0x1f,
	0xd5, 0x27, 0x98, 0x10, 0xdc, 0x37, 0x07, 0x09, 0xbb, 0x73, 0x74, 0x31, 0xf6, 0x19, 0xce, 0x1f,
	0x0a, 0x21, 0x8b, 0xeb, 0xc7, 0x87, 0xdc, 0x28, 0x9d, 0x95, 0xf8, 0x0e, 0x4e, 0x75, 0x75, 0xac,
	0x73, 0xbc, 0x24, 0x7f, 0x4f, 0xc8, 0x49, 0xc5, 0x3e, 0xc2, 0x99, 0xc7, 0xe0, 0x15, 0x8c, 0x13,
	0xbd, 0xfb, 0x99, 0x66, 0xee, 0x2e, 0x53, 0x5e, 0x57, 0x88, 0x70, 0x2c, 0x64, 0x99, 0xb8, 0x7b,
	0x9c, 0x70, 0x77, 0x5e, 0xfd, 0x1e, 0xc2, 0xd9, 0xda, 0xb5, 0xbf, 0xdb, 0x64, 0x62, 0x27, 0x0b,
	0x5c, 0xbb, 0x05, 0x6d, 0xfe, 0x63, 0x9c, 0x93, 0xfd, 0xde, 0xeb, 0x89, 0xc2, 0x7e, 0xa2, 0xcc,
	0xd9, 0x11, 0x7e, 0x80, 0x09, 0x6d, 0x39, 0xbe, 0xe8, 0xe8, 0xe8, 0x9d, 0x44, 0x2f, 0x0f, 0x41,
	0xf7, 0xc3, 0xca, 0xbd, 0x59, 0x5f, 0xcf, 0xbd, 0xfb, 0x00, 0x3c, 0x77, 0x6f, 0xdb, 0xd9, 0x11,
	0x7e, 0x03, 0x3c, 0x5c, 0x53, 0x7c, 0xd5, 0x77, 0xdf, 0x66, 0xb7, 0xa3, 0xd7, 0xff, 0xa2, 0x6d,
	0xdb, 0xed, 0xd8, 0x7d, 0x50, 0xde, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x8d, 0x28, 0x0e,
	0x60, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonHandlerClient is the client API for CommonHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonHandlerClient interface {
	GetProvinces(ctx context.Context, in *GetProvincesReq, opts ...grpc.CallOption) (*GetProvincesResp, error)
	GetCitys(ctx context.Context, in *GetCitysReq, opts ...grpc.CallOption) (*GetCitysResp, error)
	GetDistincts(ctx context.Context, in *GetDistinctsReq, opts ...grpc.CallOption) (*GetDistinctsResp, error)
	GetProvincesDetail(ctx context.Context, in *GetProvincesDetailReq, opts ...grpc.CallOption) (*GetProvincesDetailResp, error)
}

type commonHandlerClient struct {
	cc *grpc.ClientConn
}

func NewCommonHandlerClient(cc *grpc.ClientConn) CommonHandlerClient {
	return &commonHandlerClient{cc}
}

func (c *commonHandlerClient) GetProvinces(ctx context.Context, in *GetProvincesReq, opts ...grpc.CallOption) (*GetProvincesResp, error) {
	out := new(GetProvincesResp)
	err := c.cc.Invoke(ctx, "/area.CommonHandler/GetProvinces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonHandlerClient) GetCitys(ctx context.Context, in *GetCitysReq, opts ...grpc.CallOption) (*GetCitysResp, error) {
	out := new(GetCitysResp)
	err := c.cc.Invoke(ctx, "/area.CommonHandler/GetCitys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonHandlerClient) GetDistincts(ctx context.Context, in *GetDistinctsReq, opts ...grpc.CallOption) (*GetDistinctsResp, error) {
	out := new(GetDistinctsResp)
	err := c.cc.Invoke(ctx, "/area.CommonHandler/GetDistincts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonHandlerClient) GetProvincesDetail(ctx context.Context, in *GetProvincesDetailReq, opts ...grpc.CallOption) (*GetProvincesDetailResp, error) {
	out := new(GetProvincesDetailResp)
	err := c.cc.Invoke(ctx, "/area.CommonHandler/GetProvincesDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonHandlerServer is the server API for CommonHandler service.
type CommonHandlerServer interface {
	GetProvinces(context.Context, *GetProvincesReq) (*GetProvincesResp, error)
	GetCitys(context.Context, *GetCitysReq) (*GetCitysResp, error)
	GetDistincts(context.Context, *GetDistinctsReq) (*GetDistinctsResp, error)
	GetProvincesDetail(context.Context, *GetProvincesDetailReq) (*GetProvincesDetailResp, error)
}

// UnimplementedCommonHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedCommonHandlerServer struct {
}

func (*UnimplementedCommonHandlerServer) GetProvinces(ctx context.Context, req *GetProvincesReq) (*GetProvincesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinces not implemented")
}
func (*UnimplementedCommonHandlerServer) GetCitys(ctx context.Context, req *GetCitysReq) (*GetCitysResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCitys not implemented")
}
func (*UnimplementedCommonHandlerServer) GetDistincts(ctx context.Context, req *GetDistinctsReq) (*GetDistinctsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistincts not implemented")
}
func (*UnimplementedCommonHandlerServer) GetProvincesDetail(ctx context.Context, req *GetProvincesDetailReq) (*GetProvincesDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvincesDetail not implemented")
}

func RegisterCommonHandlerServer(s *grpc.Server, srv CommonHandlerServer) {
	s.RegisterService(&_CommonHandler_serviceDesc, srv)
}

func _CommonHandler_GetProvinces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvincesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonHandlerServer).GetProvinces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/area.CommonHandler/GetProvinces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonHandlerServer).GetProvinces(ctx, req.(*GetProvincesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonHandler_GetCitys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonHandlerServer).GetCitys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/area.CommonHandler/GetCitys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonHandlerServer).GetCitys(ctx, req.(*GetCitysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonHandler_GetDistincts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistinctsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonHandlerServer).GetDistincts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/area.CommonHandler/GetDistincts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonHandlerServer).GetDistincts(ctx, req.(*GetDistinctsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonHandler_GetProvincesDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvincesDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonHandlerServer).GetProvincesDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/area.CommonHandler/GetProvincesDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonHandlerServer).GetProvincesDetail(ctx, req.(*GetProvincesDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommonHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "area.CommonHandler",
	HandlerType: (*CommonHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProvinces",
			Handler:    _CommonHandler_GetProvinces_Handler,
		},
		{
			MethodName: "GetCitys",
			Handler:    _CommonHandler_GetCitys_Handler,
		},
		{
			MethodName: "GetDistincts",
			Handler:    _CommonHandler_GetDistincts_Handler,
		},
		{
			MethodName: "GetProvincesDetail",
			Handler:    _CommonHandler_GetProvincesDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "area.proto",
}
