// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"catering/coupon/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/coupon/user",
				Handler: GetUserCouponHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/coupon/info",
				Handler: GetCouponInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/coupon/draw",
				Handler: DrawCouponHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/coupon/use",
				Handler: UseCouponHandler(serverCtx),
			},
		},
	)
}
