// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integration.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserVipInfoReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetUserVipInfoReq) Reset()         { *m = GetUserVipInfoReq{} }
func (m *GetUserVipInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserVipInfoReq) ProtoMessage()    {}
func (*GetUserVipInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{0}
}

func (m *GetUserVipInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipInfoReq.Unmarshal(m, b)
}
func (m *GetUserVipInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserVipInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipInfoReq.Merge(m, src)
}
func (m *GetUserVipInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserVipInfoReq.Size(m)
}
func (m *GetUserVipInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipInfoReq proto.InternalMessageInfo

func (m *GetUserVipInfoReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserVipInfoResp struct {
	Integration          *UserIntegration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	Level                *UserVipLevel    `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-,optional"`
	XXX_unrecognized     []byte           `json:"-,optional"`
	XXX_sizecache        int32            `json:"-,optional"`
}

func (m *GetUserVipInfoResp) Reset()         { *m = GetUserVipInfoResp{} }
func (m *GetUserVipInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetUserVipInfoResp) ProtoMessage()    {}
func (*GetUserVipInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{1}
}

func (m *GetUserVipInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipInfoResp.Unmarshal(m, b)
}
func (m *GetUserVipInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipInfoResp.Marshal(b, m, deterministic)
}
func (m *GetUserVipInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipInfoResp.Merge(m, src)
}
func (m *GetUserVipInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetUserVipInfoResp.Size(m)
}
func (m *GetUserVipInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipInfoResp proto.InternalMessageInfo

func (m *GetUserVipInfoResp) GetIntegration() *UserIntegration {
	if m != nil {
		return m.Integration
	}
	return nil
}

func (m *GetUserVipInfoResp) GetLevel() *UserVipLevel {
	if m != nil {
		return m.Level
	}
	return nil
}

type GetUserIntegrationChangeLogsReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Begin                int32    `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetUserIntegrationChangeLogsReq) Reset()         { *m = GetUserIntegrationChangeLogsReq{} }
func (m *GetUserIntegrationChangeLogsReq) String() string { return proto.CompactTextString(m) }
func (*GetUserIntegrationChangeLogsReq) ProtoMessage()    {}
func (*GetUserIntegrationChangeLogsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{2}
}

func (m *GetUserIntegrationChangeLogsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIntegrationChangeLogsReq.Unmarshal(m, b)
}
func (m *GetUserIntegrationChangeLogsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIntegrationChangeLogsReq.Marshal(b, m, deterministic)
}
func (m *GetUserIntegrationChangeLogsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIntegrationChangeLogsReq.Merge(m, src)
}
func (m *GetUserIntegrationChangeLogsReq) XXX_Size() int {
	return xxx_messageInfo_GetUserIntegrationChangeLogsReq.Size(m)
}
func (m *GetUserIntegrationChangeLogsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIntegrationChangeLogsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIntegrationChangeLogsReq proto.InternalMessageInfo

func (m *GetUserIntegrationChangeLogsReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserIntegrationChangeLogsReq) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *GetUserIntegrationChangeLogsReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserIntegrationChangeLogsResp struct {
	Logs                 []*UserIntegrationLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-,optional"`
	XXX_unrecognized     []byte                `json:"-,optional"`
	XXX_sizecache        int32                 `json:"-,optional"`
}

func (m *GetUserIntegrationChangeLogsResp) Reset()         { *m = GetUserIntegrationChangeLogsResp{} }
func (m *GetUserIntegrationChangeLogsResp) String() string { return proto.CompactTextString(m) }
func (*GetUserIntegrationChangeLogsResp) ProtoMessage()    {}
func (*GetUserIntegrationChangeLogsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{3}
}

func (m *GetUserIntegrationChangeLogsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIntegrationChangeLogsResp.Unmarshal(m, b)
}
func (m *GetUserIntegrationChangeLogsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIntegrationChangeLogsResp.Marshal(b, m, deterministic)
}
func (m *GetUserIntegrationChangeLogsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIntegrationChangeLogsResp.Merge(m, src)
}
func (m *GetUserIntegrationChangeLogsResp) XXX_Size() int {
	return xxx_messageInfo_GetUserIntegrationChangeLogsResp.Size(m)
}
func (m *GetUserIntegrationChangeLogsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIntegrationChangeLogsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIntegrationChangeLogsResp proto.InternalMessageInfo

func (m *GetUserIntegrationChangeLogsResp) GetLogs() []*UserIntegrationLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type GetUserVipLevelUpLogsReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Begin                int32    `protobuf:"varint,2,opt,name=begin,proto3" json:"begin,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *GetUserVipLevelUpLogsReq) Reset()         { *m = GetUserVipLevelUpLogsReq{} }
func (m *GetUserVipLevelUpLogsReq) String() string { return proto.CompactTextString(m) }
func (*GetUserVipLevelUpLogsReq) ProtoMessage()    {}
func (*GetUserVipLevelUpLogsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{4}
}

func (m *GetUserVipLevelUpLogsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipLevelUpLogsReq.Unmarshal(m, b)
}
func (m *GetUserVipLevelUpLogsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipLevelUpLogsReq.Marshal(b, m, deterministic)
}
func (m *GetUserVipLevelUpLogsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipLevelUpLogsReq.Merge(m, src)
}
func (m *GetUserVipLevelUpLogsReq) XXX_Size() int {
	return xxx_messageInfo_GetUserVipLevelUpLogsReq.Size(m)
}
func (m *GetUserVipLevelUpLogsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipLevelUpLogsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipLevelUpLogsReq proto.InternalMessageInfo

func (m *GetUserVipLevelUpLogsReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserVipLevelUpLogsReq) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *GetUserVipLevelUpLogsReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserVipLevelUpLogsResp struct {
	Logs                 []*UserVipUpLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-,optional"`
	XXX_unrecognized     []byte          `json:"-,optional"`
	XXX_sizecache        int32           `json:"-,optional"`
}

func (m *GetUserVipLevelUpLogsResp) Reset()         { *m = GetUserVipLevelUpLogsResp{} }
func (m *GetUserVipLevelUpLogsResp) String() string { return proto.CompactTextString(m) }
func (*GetUserVipLevelUpLogsResp) ProtoMessage()    {}
func (*GetUserVipLevelUpLogsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{5}
}

func (m *GetUserVipLevelUpLogsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipLevelUpLogsResp.Unmarshal(m, b)
}
func (m *GetUserVipLevelUpLogsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipLevelUpLogsResp.Marshal(b, m, deterministic)
}
func (m *GetUserVipLevelUpLogsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipLevelUpLogsResp.Merge(m, src)
}
func (m *GetUserVipLevelUpLogsResp) XXX_Size() int {
	return xxx_messageInfo_GetUserVipLevelUpLogsResp.Size(m)
}
func (m *GetUserVipLevelUpLogsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipLevelUpLogsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipLevelUpLogsResp proto.InternalMessageInfo

func (m *GetUserVipLevelUpLogsResp) GetLogs() []*UserVipUpLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ChangeUserIntegrationReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ChangeValue          int32    `protobuf:"varint,2,opt,name=change_value,json=changeValue,proto3" json:"change_value,omitempty"`
	ChangeType           int32    `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	IsAdd                int32    `protobuf:"varint,4,opt,name=is_add,json=isAdd,proto3" json:"is_add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *ChangeUserIntegrationReq) Reset()         { *m = ChangeUserIntegrationReq{} }
func (m *ChangeUserIntegrationReq) String() string { return proto.CompactTextString(m) }
func (*ChangeUserIntegrationReq) ProtoMessage()    {}
func (*ChangeUserIntegrationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{6}
}

func (m *ChangeUserIntegrationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserIntegrationReq.Unmarshal(m, b)
}
func (m *ChangeUserIntegrationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserIntegrationReq.Marshal(b, m, deterministic)
}
func (m *ChangeUserIntegrationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserIntegrationReq.Merge(m, src)
}
func (m *ChangeUserIntegrationReq) XXX_Size() int {
	return xxx_messageInfo_ChangeUserIntegrationReq.Size(m)
}
func (m *ChangeUserIntegrationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserIntegrationReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserIntegrationReq proto.InternalMessageInfo

func (m *ChangeUserIntegrationReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChangeUserIntegrationReq) GetChangeValue() int32 {
	if m != nil {
		return m.ChangeValue
	}
	return 0
}

func (m *ChangeUserIntegrationReq) GetChangeType() int32 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *ChangeUserIntegrationReq) GetIsAdd() int32 {
	if m != nil {
		return m.IsAdd
	}
	return 0
}

type ChangeUserIntegrationResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *ChangeUserIntegrationResp) Reset()         { *m = ChangeUserIntegrationResp{} }
func (m *ChangeUserIntegrationResp) String() string { return proto.CompactTextString(m) }
func (*ChangeUserIntegrationResp) ProtoMessage()    {}
func (*ChangeUserIntegrationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{7}
}

func (m *ChangeUserIntegrationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUserIntegrationResp.Unmarshal(m, b)
}
func (m *ChangeUserIntegrationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUserIntegrationResp.Marshal(b, m, deterministic)
}
func (m *ChangeUserIntegrationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUserIntegrationResp.Merge(m, src)
}
func (m *ChangeUserIntegrationResp) XXX_Size() int {
	return xxx_messageInfo_ChangeUserIntegrationResp.Size(m)
}
func (m *ChangeUserIntegrationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUserIntegrationResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUserIntegrationResp proto.InternalMessageInfo

type UserVipLevel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LevelName            string   `protobuf:"bytes,2,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`
	UpNeedIntegration    int64    `protobuf:"varint,3,opt,name=up_need_integration,json=upNeedIntegration,proto3" json:"up_need_integration,omitempty"`
	LevelDiscount        int32    `protobuf:"varint,4,opt,name=level_discount,json=levelDiscount,proto3" json:"level_discount,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,5,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	NextLevelId          int64    `protobuf:"varint,6,opt,name=next_level_id,json=nextLevelId,proto3" json:"next_level_id,omitempty"`
	NextLevelName        string   `protobuf:"bytes,7,opt,name=next_level_name,json=nextLevelName,proto3" json:"next_level_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserVipLevel) Reset()         { *m = UserVipLevel{} }
func (m *UserVipLevel) String() string { return proto.CompactTextString(m) }
func (*UserVipLevel) ProtoMessage()    {}
func (*UserVipLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{8}
}

func (m *UserVipLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVipLevel.Unmarshal(m, b)
}
func (m *UserVipLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVipLevel.Marshal(b, m, deterministic)
}
func (m *UserVipLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVipLevel.Merge(m, src)
}
func (m *UserVipLevel) XXX_Size() int {
	return xxx_messageInfo_UserVipLevel.Size(m)
}
func (m *UserVipLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVipLevel.DiscardUnknown(m)
}

var xxx_messageInfo_UserVipLevel proto.InternalMessageInfo

func (m *UserVipLevel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserVipLevel) GetLevelName() string {
	if m != nil {
		return m.LevelName
	}
	return ""
}

func (m *UserVipLevel) GetUpNeedIntegration() int64 {
	if m != nil {
		return m.UpNeedIntegration
	}
	return 0
}

func (m *UserVipLevel) GetLevelDiscount() int32 {
	if m != nil {
		return m.LevelDiscount
	}
	return 0
}

func (m *UserVipLevel) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *UserVipLevel) GetNextLevelId() int64 {
	if m != nil {
		return m.NextLevelId
	}
	return 0
}

func (m *UserVipLevel) GetNextLevelName() string {
	if m != nil {
		return m.NextLevelName
	}
	return ""
}

type UserVipUpLog struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	BeforeLevelId        int64    `protobuf:"varint,3,opt,name=before_level_id,json=beforeLevelId,proto3" json:"before_level_id,omitempty"`
	AfterLevelId         int64    `protobuf:"varint,4,opt,name=after_level_id,json=afterLevelId,proto3" json:"after_level_id,omitempty"`
	UpTime               string   `protobuf:"bytes,5,opt,name=up_time,json=upTime,proto3" json:"up_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserVipUpLog) Reset()         { *m = UserVipUpLog{} }
func (m *UserVipUpLog) String() string { return proto.CompactTextString(m) }
func (*UserVipUpLog) ProtoMessage()    {}
func (*UserVipUpLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{9}
}

func (m *UserVipUpLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVipUpLog.Unmarshal(m, b)
}
func (m *UserVipUpLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVipUpLog.Marshal(b, m, deterministic)
}
func (m *UserVipUpLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVipUpLog.Merge(m, src)
}
func (m *UserVipUpLog) XXX_Size() int {
	return xxx_messageInfo_UserVipUpLog.Size(m)
}
func (m *UserVipUpLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVipUpLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserVipUpLog proto.InternalMessageInfo

func (m *UserVipUpLog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserVipUpLog) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserVipUpLog) GetBeforeLevelId() int64 {
	if m != nil {
		return m.BeforeLevelId
	}
	return 0
}

func (m *UserVipUpLog) GetAfterLevelId() int64 {
	if m != nil {
		return m.AfterLevelId
	}
	return 0
}

func (m *UserVipUpLog) GetUpTime() string {
	if m != nil {
		return m.UpTime
	}
	return ""
}

type UserIntegration struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	CurrentIntegration   int64    `protobuf:"varint,3,opt,name=current_integration,json=currentIntegration,proto3" json:"current_integration,omitempty"`
	HistoryIntegration   int64    `protobuf:"varint,4,opt,name=history_integration,json=historyIntegration,proto3" json:"history_integration,omitempty"`
	UpdatedTime          string   `protobuf:"bytes,5,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	CreatedTime          string   `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	ConsumeIntegration   int64    `protobuf:"varint,7,opt,name=consume_integration,json=consumeIntegration,proto3" json:"consume_integration,omitempty"`
	LevelId              int64    `protobuf:"varint,8,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserIntegration) Reset()         { *m = UserIntegration{} }
func (m *UserIntegration) String() string { return proto.CompactTextString(m) }
func (*UserIntegration) ProtoMessage()    {}
func (*UserIntegration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{10}
}

func (m *UserIntegration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIntegration.Unmarshal(m, b)
}
func (m *UserIntegration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIntegration.Marshal(b, m, deterministic)
}
func (m *UserIntegration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIntegration.Merge(m, src)
}
func (m *UserIntegration) XXX_Size() int {
	return xxx_messageInfo_UserIntegration.Size(m)
}
func (m *UserIntegration) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIntegration.DiscardUnknown(m)
}

var xxx_messageInfo_UserIntegration proto.InternalMessageInfo

func (m *UserIntegration) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserIntegration) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserIntegration) GetCurrentIntegration() int64 {
	if m != nil {
		return m.CurrentIntegration
	}
	return 0
}

func (m *UserIntegration) GetHistoryIntegration() int64 {
	if m != nil {
		return m.HistoryIntegration
	}
	return 0
}

func (m *UserIntegration) GetUpdatedTime() string {
	if m != nil {
		return m.UpdatedTime
	}
	return ""
}

func (m *UserIntegration) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *UserIntegration) GetConsumeIntegration() int64 {
	if m != nil {
		return m.ConsumeIntegration
	}
	return 0
}

func (m *UserIntegration) GetLevelId() int64 {
	if m != nil {
		return m.LevelId
	}
	return 0
}

type UserIntegrationLog struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ChangeType           int64    `protobuf:"varint,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	ChangeValue          int64    `protobuf:"varint,4,opt,name=change_value,json=changeValue,proto3" json:"change_value,omitempty"`
	BeforeValue          int64    `protobuf:"varint,5,opt,name=before_value,json=beforeValue,proto3" json:"before_value,omitempty"`
	AfterValue           int64    `protobuf:"varint,6,opt,name=after_value,json=afterValue,proto3" json:"after_value,omitempty"`
	ChangeTime           string   `protobuf:"bytes,7,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-,optional"`
	XXX_unrecognized     []byte   `json:"-,optional"`
	XXX_sizecache        int32    `json:"-,optional"`
}

func (m *UserIntegrationLog) Reset()         { *m = UserIntegrationLog{} }
func (m *UserIntegrationLog) String() string { return proto.CompactTextString(m) }
func (*UserIntegrationLog) ProtoMessage()    {}
func (*UserIntegrationLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47e644ecb1478e7, []int{11}
}

func (m *UserIntegrationLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIntegrationLog.Unmarshal(m, b)
}
func (m *UserIntegrationLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIntegrationLog.Marshal(b, m, deterministic)
}
func (m *UserIntegrationLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIntegrationLog.Merge(m, src)
}
func (m *UserIntegrationLog) XXX_Size() int {
	return xxx_messageInfo_UserIntegrationLog.Size(m)
}
func (m *UserIntegrationLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIntegrationLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserIntegrationLog proto.InternalMessageInfo

func (m *UserIntegrationLog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserIntegrationLog) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserIntegrationLog) GetChangeType() int64 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *UserIntegrationLog) GetChangeValue() int64 {
	if m != nil {
		return m.ChangeValue
	}
	return 0
}

func (m *UserIntegrationLog) GetBeforeValue() int64 {
	if m != nil {
		return m.BeforeValue
	}
	return 0
}

func (m *UserIntegrationLog) GetAfterValue() int64 {
	if m != nil {
		return m.AfterValue
	}
	return 0
}

func (m *UserIntegrationLog) GetChangeTime() string {
	if m != nil {
		return m.ChangeTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserVipInfoReq)(nil), "proto.GetUserVipInfoReq")
	proto.RegisterType((*GetUserVipInfoResp)(nil), "proto.GetUserVipInfoResp")
	proto.RegisterType((*GetUserIntegrationChangeLogsReq)(nil), "proto.GetUserIntegrationChangeLogsReq")
	proto.RegisterType((*GetUserIntegrationChangeLogsResp)(nil), "proto.GetUserIntegrationChangeLogsResp")
	proto.RegisterType((*GetUserVipLevelUpLogsReq)(nil), "proto.GetUserVipLevelUpLogsReq")
	proto.RegisterType((*GetUserVipLevelUpLogsResp)(nil), "proto.GetUserVipLevelUpLogsResp")
	proto.RegisterType((*ChangeUserIntegrationReq)(nil), "proto.ChangeUserIntegrationReq")
	proto.RegisterType((*ChangeUserIntegrationResp)(nil), "proto.ChangeUserIntegrationResp")
	proto.RegisterType((*UserVipLevel)(nil), "proto.UserVipLevel")
	proto.RegisterType((*UserVipUpLog)(nil), "proto.UserVipUpLog")
	proto.RegisterType((*UserIntegration)(nil), "proto.UserIntegration")
	proto.RegisterType((*UserIntegrationLog)(nil), "proto.UserIntegrationLog")
}

func init() { proto.RegisterFile("integration.proto", fileDescriptor_a47e644ecb1478e7) }

var fileDescriptor_a47e644ecb1478e7 = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x4f, 0xdb, 0x40,
	0x10, 0x26, 0x09, 0x49, 0x60, 0xf2, 0xa0, 0x6c, 0x4a, 0xeb, 0xd0, 0x56, 0x04, 0xab, 0x3c, 0x7a,
	0x28, 0x48, 0xf4, 0xd2, 0x6b, 0x55, 0x24, 0x8a, 0x84, 0x90, 0x6a, 0x01, 0xea, 0xa1, 0x92, 0x65,
	0xd8, 0x21, 0xac, 0x94, 0xd8, 0x8b, 0x1f, 0xa8, 0x39, 0xf7, 0xd0, 0x4b, 0xef, 0xfd, 0x09, 0xfd,
	0x59, 0xfd, 0x2b, 0x95, 0x77, 0x36, 0xce, 0x3a, 0x71, 0x68, 0x0e, 0x3d, 0x25, 0xfb, 0xcd, 0xb7,
	0x33, 0xdf, 0x3c, 0x76, 0x0c, 0xeb, 0xc2, 0x8f, 0xb1, 0x1f, 0x7a, 0xb1, 0x08, 0xfc, 0x03, 0x19,
	0x06, 0x71, 0xc0, 0xaa, 0xea, 0xc7, 0xde, 0x81, 0xf5, 0x13, 0x8c, 0x2f, 0x23, 0x0c, 0xaf, 0x84,
	0x3c, 0xf5, 0x6f, 0x03, 0x07, 0xef, 0xd9, 0x13, 0xa8, 0x24, 0x82, 0x5b, 0xa5, 0x5e, 0x69, 0xbf,
	0xe2, 0xa4, 0x7f, 0xed, 0x11, 0xb0, 0x69, 0x5a, 0x24, 0xd9, 0x7b, 0x68, 0x18, 0x8e, 0x15, 0xbf,
	0x71, 0xf4, 0x8c, 0x02, 0x1c, 0xa4, 0xe4, 0xd3, 0x89, 0xd5, 0x31, 0xa9, 0xec, 0x0d, 0x54, 0x07,
	0xf8, 0x80, 0x03, 0xab, 0xac, 0xee, 0x74, 0x8c, 0x3b, 0x57, 0x42, 0x9e, 0xa5, 0x26, 0x87, 0x18,
	0xb6, 0x0b, 0x5b, 0x3a, 0xb4, 0xe1, 0xed, 0xe3, 0x9d, 0xe7, 0xf7, 0xf1, 0x2c, 0xe8, 0x47, 0x85,
	0x7a, 0xd9, 0x53, 0xa8, 0x5e, 0x63, 0x5f, 0xf8, 0xca, 0x7f, 0xd5, 0xa1, 0x43, 0x8a, 0xde, 0x04,
	0x89, 0x1f, 0x5b, 0x15, 0x42, 0xd5, 0xc1, 0xfe, 0x0c, 0xbd, 0xc7, 0x03, 0x44, 0x92, 0xbd, 0x85,
	0xe5, 0x41, 0xd0, 0x8f, 0xac, 0x52, 0xaf, 0xb2, 0xdf, 0x38, 0xea, 0x16, 0xa7, 0x78, 0x16, 0xf4,
	0x1d, 0x45, 0xb3, 0xbf, 0x80, 0x35, 0x29, 0x97, 0xca, 0xe6, 0x52, 0xfe, 0x1f, 0xb1, 0xc7, 0xd0,
	0x9d, 0xe3, 0x39, 0x92, 0x6c, 0x2f, 0xa7, 0x72, 0xaa, 0xa8, 0x8a, 0xa7, 0xf5, 0xfd, 0x28, 0x81,
	0x45, 0x19, 0x4e, 0x77, 0xa9, 0x50, 0xe0, 0x36, 0x34, 0x6f, 0x14, 0xdb, 0x7d, 0xf0, 0x06, 0x09,
	0x6a, 0x9d, 0x0d, 0xc2, 0xae, 0x52, 0x88, 0x6d, 0x81, 0x3e, 0xba, 0xf1, 0x48, 0xa2, 0xd6, 0x0c,
	0x04, 0x5d, 0x8c, 0x24, 0xb2, 0x0d, 0xa8, 0x89, 0xc8, 0xf5, 0x38, 0xb7, 0x96, 0x29, 0x1f, 0x11,
	0x7d, 0xe0, 0xdc, 0x7e, 0x01, 0xdd, 0x39, 0x42, 0x22, 0x69, 0x7f, 0x2f, 0x43, 0xd3, 0x4c, 0x95,
	0xb5, 0xa1, 0x9c, 0x29, 0x2b, 0x0b, 0xce, 0x5e, 0x01, 0xa8, 0x21, 0x71, 0x7d, 0x6f, 0x48, 0xb2,
	0x56, 0x9d, 0x55, 0x85, 0x9c, 0x7b, 0x43, 0x64, 0x07, 0xd0, 0x49, 0xa4, 0xeb, 0x23, 0x72, 0xd7,
	0x9c, 0xd3, 0x8a, 0xba, 0xbf, 0x9e, 0xc8, 0x73, 0x44, 0x6e, 0xc4, 0x64, 0x3b, 0xd0, 0x26, 0x77,
	0x5c, 0x44, 0x54, 0x7b, 0xd2, 0xda, 0x52, 0xe8, 0xb1, 0x06, 0xd3, 0x72, 0x24, 0x92, 0x7b, 0x31,
	0x72, 0x37, 0x16, 0x43, 0xb4, 0xaa, 0x2a, 0x6e, 0x43, 0x63, 0x17, 0x62, 0x88, 0xcc, 0x86, 0x96,
	0x8f, 0xdf, 0x62, 0x97, 0xdc, 0x09, 0x6e, 0xd5, 0x54, 0xcc, 0x46, 0x0a, 0xaa, 0x54, 0x4e, 0x39,
	0xdb, 0x85, 0x35, 0x83, 0xa3, 0x32, 0xa8, 0x2b, 0x4f, 0xad, 0x8c, 0x95, 0x66, 0x61, 0xff, 0x2a,
	0x65, 0x55, 0x50, 0x3d, 0x9c, 0xa9, 0x82, 0x6e, 0x58, 0x79, 0xd2, 0xb0, 0x5d, 0x58, 0xbb, 0xc6,
	0xdb, 0x20, 0xc4, 0x89, 0x00, 0x4a, 0xba, 0x45, 0xf0, 0x58, 0xc2, 0x6b, 0x68, 0x7b, 0xb7, 0x31,
	0x86, 0x13, 0xda, 0xb2, 0xa2, 0x35, 0x15, 0x3a, 0x66, 0x3d, 0x87, 0x7a, 0x22, 0xcd, 0x54, 0x6b,
	0x89, 0x4c, 0xb3, 0xb4, 0x7f, 0x97, 0x61, 0x6d, 0xaa, 0x6f, 0x0b, 0x88, 0x3b, 0x84, 0xce, 0x4d,
	0x12, 0x86, 0xe8, 0xc7, 0x05, 0x5d, 0x61, 0xda, 0x64, 0xba, 0x3c, 0x84, 0xce, 0x9d, 0x88, 0xe2,
	0x20, 0x1c, 0xe5, 0x2e, 0x90, 0x54, 0xa6, 0x4d, 0xe6, 0x85, 0x05, 0x1a, 0x94, 0x8e, 0x74, 0x88,
	0x13, 0x4a, 0x8d, 0x28, 0x1a, 0x53, 0x94, 0x54, 0x67, 0xe0, 0x47, 0xc9, 0x10, 0x73, 0x61, 0xeb,
	0x5a, 0x27, 0x99, 0xcc, 0xb0, 0x5d, 0x58, 0xc9, 0xea, 0xb8, 0xa2, 0x58, 0xf5, 0x01, 0x95, 0xd0,
	0xfe, 0x53, 0x02, 0x36, 0xbb, 0x2d, 0x16, 0x28, 0x56, 0xc1, 0xbb, 0xaa, 0xe4, 0xde, 0xd5, 0xf4,
	0xdb, 0xa4, 0xaa, 0xe4, 0xde, 0xe6, 0x36, 0x34, 0xf5, 0x34, 0x10, 0xa5, 0x4a, 0x14, 0xc2, 0xb2,
	0xe7, 0x4b, 0x83, 0x40, 0x0c, 0x9a, 0x56, 0x50, 0xd0, 0xcc, 0xfb, 0x16, 0xd9, 0xa0, 0x8e, 0x75,
	0x88, 0x21, 0x1e, 0xfd, 0xac, 0x00, 0x33, 0xb2, 0xfb, 0xe4, 0xf9, 0x7c, 0x80, 0x21, 0xbb, 0x87,
	0x97, 0x8f, 0x2d, 0x57, 0xb6, 0xab, 0x97, 0xd4, 0x3f, 0x56, 0xfc, 0xe6, 0xde, 0x42, 0xbc, 0x48,
	0xda, 0x4b, 0xec, 0x2b, 0x6c, 0x14, 0xae, 0x48, 0xb6, 0x95, 0xf7, 0x31, 0xb3, 0x9a, 0x37, 0x7b,
	0x8f, 0x13, 0xc6, 0xde, 0x0b, 0x17, 0x56, 0xe6, 0x7d, 0xde, 0x5e, 0xcd, 0xbc, 0xcf, 0xdf, 0x77,
	0x4b, 0xec, 0x04, 0xda, 0xf9, 0xef, 0x2c, 0xb3, 0x66, 0x34, 0xe9, 0xaf, 0xf4, 0x66, 0x77, 0x8e,
	0x25, 0x75, 0x74, 0x5d, 0x53, 0xb6, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc0, 0xa7,
	0x13, 0xfa, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntegrationHandlerClient is the client API for IntegrationHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntegrationHandlerClient interface {
	GetUserIntegrationChangeLogs(ctx context.Context, in *GetUserIntegrationChangeLogsReq, opts ...grpc.CallOption) (*GetUserIntegrationChangeLogsResp, error)
	GetUserVipLevelUpLogs(ctx context.Context, in *GetUserVipLevelUpLogsReq, opts ...grpc.CallOption) (*GetUserVipLevelUpLogsResp, error)
	ChangeUserIntegration(ctx context.Context, in *ChangeUserIntegrationReq, opts ...grpc.CallOption) (*ChangeUserIntegrationResp, error)
	GetUserVipInfo(ctx context.Context, in *GetUserVipInfoReq, opts ...grpc.CallOption) (*GetUserVipInfoResp, error)
}

type integrationHandlerClient struct {
	cc *grpc.ClientConn
}

func NewIntegrationHandlerClient(cc *grpc.ClientConn) IntegrationHandlerClient {
	return &integrationHandlerClient{cc}
}

func (c *integrationHandlerClient) GetUserIntegrationChangeLogs(ctx context.Context, in *GetUserIntegrationChangeLogsReq, opts ...grpc.CallOption) (*GetUserIntegrationChangeLogsResp, error) {
	out := new(GetUserIntegrationChangeLogsResp)
	err := c.cc.Invoke(ctx, "/proto.IntegrationHandler/GetUserIntegrationChangeLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) GetUserVipLevelUpLogs(ctx context.Context, in *GetUserVipLevelUpLogsReq, opts ...grpc.CallOption) (*GetUserVipLevelUpLogsResp, error) {
	out := new(GetUserVipLevelUpLogsResp)
	err := c.cc.Invoke(ctx, "/proto.IntegrationHandler/GetUserVipLevelUpLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) ChangeUserIntegration(ctx context.Context, in *ChangeUserIntegrationReq, opts ...grpc.CallOption) (*ChangeUserIntegrationResp, error) {
	out := new(ChangeUserIntegrationResp)
	err := c.cc.Invoke(ctx, "/proto.IntegrationHandler/ChangeUserIntegration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) GetUserVipInfo(ctx context.Context, in *GetUserVipInfoReq, opts ...grpc.CallOption) (*GetUserVipInfoResp, error) {
	out := new(GetUserVipInfoResp)
	err := c.cc.Invoke(ctx, "/proto.IntegrationHandler/GetUserVipInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationHandlerServer is the server API for IntegrationHandler service.
type IntegrationHandlerServer interface {
	GetUserIntegrationChangeLogs(context.Context, *GetUserIntegrationChangeLogsReq) (*GetUserIntegrationChangeLogsResp, error)
	GetUserVipLevelUpLogs(context.Context, *GetUserVipLevelUpLogsReq) (*GetUserVipLevelUpLogsResp, error)
	ChangeUserIntegration(context.Context, *ChangeUserIntegrationReq) (*ChangeUserIntegrationResp, error)
	GetUserVipInfo(context.Context, *GetUserVipInfoReq) (*GetUserVipInfoResp, error)
}

// UnimplementedIntegrationHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedIntegrationHandlerServer struct {
}

func (*UnimplementedIntegrationHandlerServer) GetUserIntegrationChangeLogs(ctx context.Context, req *GetUserIntegrationChangeLogsReq) (*GetUserIntegrationChangeLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIntegrationChangeLogs not implemented")
}
func (*UnimplementedIntegrationHandlerServer) GetUserVipLevelUpLogs(ctx context.Context, req *GetUserVipLevelUpLogsReq) (*GetUserVipLevelUpLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVipLevelUpLogs not implemented")
}
func (*UnimplementedIntegrationHandlerServer) ChangeUserIntegration(ctx context.Context, req *ChangeUserIntegrationReq) (*ChangeUserIntegrationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserIntegration not implemented")
}
func (*UnimplementedIntegrationHandlerServer) GetUserVipInfo(ctx context.Context, req *GetUserVipInfoReq) (*GetUserVipInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVipInfo not implemented")
}

func RegisterIntegrationHandlerServer(s *grpc.Server, srv IntegrationHandlerServer) {
	s.RegisterService(&_IntegrationHandler_serviceDesc, srv)
}

func _IntegrationHandler_GetUserIntegrationChangeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIntegrationChangeLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).GetUserIntegrationChangeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IntegrationHandler/GetUserIntegrationChangeLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).GetUserIntegrationChangeLogs(ctx, req.(*GetUserIntegrationChangeLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_GetUserVipLevelUpLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserVipLevelUpLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).GetUserVipLevelUpLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IntegrationHandler/GetUserVipLevelUpLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).GetUserVipLevelUpLogs(ctx, req.(*GetUserVipLevelUpLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_ChangeUserIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserIntegrationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).ChangeUserIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IntegrationHandler/ChangeUserIntegration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).ChangeUserIntegration(ctx, req.(*ChangeUserIntegrationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_GetUserVipInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserVipInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).GetUserVipInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IntegrationHandler/GetUserVipInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).GetUserVipInfo(ctx, req.(*GetUserVipInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IntegrationHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IntegrationHandler",
	HandlerType: (*IntegrationHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserIntegrationChangeLogs",
			Handler:    _IntegrationHandler_GetUserIntegrationChangeLogs_Handler,
		},
		{
			MethodName: "GetUserVipLevelUpLogs",
			Handler:    _IntegrationHandler_GetUserVipLevelUpLogs_Handler,
		},
		{
			MethodName: "ChangeUserIntegration",
			Handler:    _IntegrationHandler_ChangeUserIntegration_Handler,
		},
		{
			MethodName: "GetUserVipInfo",
			Handler:    _IntegrationHandler_GetUserVipInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration.proto",
}
