// Code generated by goctl. DO NOT EDIT!
// Source: advertisement.proto

package server

import (
	"context"

	"catering/advertisement/rpc/internal/logic"
	"catering/advertisement/rpc/internal/svc"
	"catering/proto/advertisement"
)

type AdvertisementHandlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewAdvertisementHandlerServer(svcCtx *svc.ServiceContext) *AdvertisementHandlerServer {
	return &AdvertisementHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *AdvertisementHandlerServer) AdBannerList(ctx context.Context, in *proto.GetAdBannerListReq) (*proto.GetAdBannerListResp, error) {
	l := logic.NewAdBannerListLogic(ctx, s.svcCtx)
	return l.AdBannerList(in)
}

func (s *AdvertisementHandlerServer) AdHotActivities(ctx context.Context, in *proto.GetAdHotActivitieReq) (*proto.GetAdHotActivitieResp, error) {
	l := logic.NewAdHotActivitiesLogic(ctx, s.svcCtx)
	return l.AdHotActivities(in)
}

func (s *AdvertisementHandlerServer) AdRecommendDailyProducts(ctx context.Context, in *proto.GetAdRecommendDailyProductReq) (*proto.GetAdRecommendDailyProductResp, error) {
	l := logic.NewAdRecommendDailyProductsLogic(ctx, s.svcCtx)
	return l.AdRecommendDailyProducts(in)
}
