// Code generated by goctl. DO NOT EDIT!
// Source: voucher.proto

package server

import (
	"context"

	proto "catering/proto/voucher"
	"catering/voucher/rpc/internal/logic"
	"catering/voucher/rpc/internal/svc"
)

type VoucherHandlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewVoucherHandlerServer(svcCtx *svc.ServiceContext) *VoucherHandlerServer {
	return &VoucherHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *VoucherHandlerServer) GetUserVoucher(ctx context.Context, in *proto.GetUserVoucherReq) (*proto.GetUserVoucherResp, error) {
	l := logic.NewGetUserVoucherLogic(ctx, s.svcCtx)
	return l.GetUserVoucher(in)
}

func (s *VoucherHandlerServer) DrawVoucher(ctx context.Context, in *proto.DrawVoucherReq) (*proto.DrawVoucherResp, error) {
	l := logic.NewDrawVoucherLogic(ctx, s.svcCtx)
	return l.DrawVoucher(in)
}

func (s *VoucherHandlerServer) GetVoucherInfo(ctx context.Context, in *proto.GetVoucherInfoReq) (*proto.GetVoucherInfoResp, error) {
	l := logic.NewGetVoucherInfoLogic(ctx, s.svcCtx)
	return l.GetVoucherInfo(in)
}

func (s *VoucherHandlerServer) UseVoucher(ctx context.Context, in *proto.UseVoucherReq) (*proto.UseVoucherResp, error) {
	l := logic.NewUseVoucherLogic(ctx, s.svcCtx)
	return l.UseVoucher(in)
}
