Name: product.rpc
ListenOn: 127.0.0.1:8080
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
Mysql: 
  DataSource: root:root@tcp(localhost:3306)/test
  MaxIdle: 10
  MaxOpen: 10
Cache:
  - Host: localhost:6379