// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package productBase

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductInfo struct {
	Base                 *ProductBase        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Batchs               []*ProductBatch     `protobuf:"bytes,2,rep,name=batchs,proto3" json:"batchs,omitempty"`
	Attributes           []*ProductAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Category             *ProductCategory    `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProductInfo) Reset()         { *m = ProductInfo{} }
func (m *ProductInfo) String() string { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()    {}
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *ProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductInfo.Unmarshal(m, b)
}
func (m *ProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductInfo.Marshal(b, m, deterministic)
}
func (m *ProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductInfo.Merge(m, src)
}
func (m *ProductInfo) XXX_Size() int {
	return xxx_messageInfo_ProductInfo.Size(m)
}
func (m *ProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProductInfo proto.InternalMessageInfo

func (m *ProductInfo) GetBase() *ProductBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ProductInfo) GetBatchs() []*ProductBatch {
	if m != nil {
		return m.Batchs
	}
	return nil
}

func (m *ProductInfo) GetAttributes() []*ProductAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ProductInfo) GetCategory() *ProductCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

type ProductBase struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName          string   `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Specis               int64    `protobuf:"varint,4,opt,name=specis,proto3" json:"specis,omitempty"`
	PicUrl               string   `protobuf:"bytes,5,opt,name=picUrl,proto3" json:"picUrl,omitempty"`
	OldMoney             int64    `protobuf:"varint,6,opt,name=oldMoney,proto3" json:"oldMoney,omitempty"`
	Money                int64    `protobuf:"varint,7,opt,name=money,proto3" json:"money,omitempty"`
	CategoryId           int64    `protobuf:"varint,8,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Sort                 int32    `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductBase) Reset()         { *m = ProductBase{} }
func (m *ProductBase) String() string { return proto.CompactTextString(m) }
func (*ProductBase) ProtoMessage()    {}
func (*ProductBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *ProductBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductBase.Unmarshal(m, b)
}
func (m *ProductBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductBase.Marshal(b, m, deterministic)
}
func (m *ProductBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductBase.Merge(m, src)
}
func (m *ProductBase) XXX_Size() int {
	return xxx_messageInfo_ProductBase.Size(m)
}
func (m *ProductBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductBase.DiscardUnknown(m)
}

var xxx_messageInfo_ProductBase proto.InternalMessageInfo

func (m *ProductBase) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductBase) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *ProductBase) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductBase) GetSpecis() int64 {
	if m != nil {
		return m.Specis
	}
	return 0
}

func (m *ProductBase) GetPicUrl() string {
	if m != nil {
		return m.PicUrl
	}
	return ""
}

func (m *ProductBase) GetOldMoney() int64 {
	if m != nil {
		return m.OldMoney
	}
	return 0
}

func (m *ProductBase) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *ProductBase) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *ProductBase) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type ProductCategory struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName         string   `protobuf:"bytes,2,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	Sort                 int32    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductCategory) Reset()         { *m = ProductCategory{} }
func (m *ProductCategory) String() string { return proto.CompactTextString(m) }
func (*ProductCategory) ProtoMessage()    {}
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ProductCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCategory.Unmarshal(m, b)
}
func (m *ProductCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCategory.Marshal(b, m, deterministic)
}
func (m *ProductCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCategory.Merge(m, src)
}
func (m *ProductCategory) XXX_Size() int {
	return xxx_messageInfo_ProductCategory.Size(m)
}
func (m *ProductCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCategory.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCategory proto.InternalMessageInfo

func (m *ProductCategory) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductCategory) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *ProductCategory) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type ProductDetail struct {
	Product              *ProductInfo   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ChildProduct         []*ProductInfo `protobuf:"bytes,2,rep,name=childProduct,proto3" json:"childProduct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProductDetail) Reset()         { *m = ProductDetail{} }
func (m *ProductDetail) String() string { return proto.CompactTextString(m) }
func (*ProductDetail) ProtoMessage()    {}
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *ProductDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDetail.Unmarshal(m, b)
}
func (m *ProductDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDetail.Marshal(b, m, deterministic)
}
func (m *ProductDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDetail.Merge(m, src)
}
func (m *ProductDetail) XXX_Size() int {
	return xxx_messageInfo_ProductDetail.Size(m)
}
func (m *ProductDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDetail proto.InternalMessageInfo

func (m *ProductDetail) GetProduct() *ProductInfo {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductDetail) GetChildProduct() []*ProductInfo {
	if m != nil {
		return m.ChildProduct
	}
	return nil
}

type ProductBatch struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BatchName            string   `protobuf:"bytes,2,opt,name=batchName,proto3" json:"batchName,omitempty"`
	Sort                 int32    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductBatch) Reset()         { *m = ProductBatch{} }
func (m *ProductBatch) String() string { return proto.CompactTextString(m) }
func (*ProductBatch) ProtoMessage()    {}
func (*ProductBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *ProductBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductBatch.Unmarshal(m, b)
}
func (m *ProductBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductBatch.Marshal(b, m, deterministic)
}
func (m *ProductBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductBatch.Merge(m, src)
}
func (m *ProductBatch) XXX_Size() int {
	return xxx_messageInfo_ProductBatch.Size(m)
}
func (m *ProductBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductBatch.DiscardUnknown(m)
}

var xxx_messageInfo_ProductBatch proto.InternalMessageInfo

func (m *ProductBatch) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductBatch) GetBatchName() string {
	if m != nil {
		return m.BatchName
	}
	return ""
}

func (m *ProductBatch) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type ProductAttribute struct {
	Id                   int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeName        string                   `protobuf:"bytes,2,opt,name=attributeName,proto3" json:"attributeName,omitempty"`
	Sort                 int32                    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	AttributeValues      []*ProductAttributeValue `protobuf:"bytes,4,rep,name=attributeValues,proto3" json:"attributeValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProductAttribute) Reset()         { *m = ProductAttribute{} }
func (m *ProductAttribute) String() string { return proto.CompactTextString(m) }
func (*ProductAttribute) ProtoMessage()    {}
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *ProductAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttribute.Unmarshal(m, b)
}
func (m *ProductAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttribute.Marshal(b, m, deterministic)
}
func (m *ProductAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttribute.Merge(m, src)
}
func (m *ProductAttribute) XXX_Size() int {
	return xxx_messageInfo_ProductAttribute.Size(m)
}
func (m *ProductAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttribute proto.InternalMessageInfo

func (m *ProductAttribute) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductAttribute) GetAttributeName() string {
	if m != nil {
		return m.AttributeName
	}
	return ""
}

func (m *ProductAttribute) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ProductAttribute) GetAttributeValues() []*ProductAttributeValue {
	if m != nil {
		return m.AttributeValues
	}
	return nil
}

type ProductAttributeValue struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sort                 int32    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductAttributeValue) Reset()         { *m = ProductAttributeValue{} }
func (m *ProductAttributeValue) String() string { return proto.CompactTextString(m) }
func (*ProductAttributeValue) ProtoMessage()    {}
func (*ProductAttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *ProductAttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttributeValue.Unmarshal(m, b)
}
func (m *ProductAttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttributeValue.Marshal(b, m, deterministic)
}
func (m *ProductAttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttributeValue.Merge(m, src)
}
func (m *ProductAttributeValue) XXX_Size() int {
	return xxx_messageInfo_ProductAttributeValue.Size(m)
}
func (m *ProductAttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttributeValue proto.InternalMessageInfo

func (m *ProductAttributeValue) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductAttributeValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ProductAttributeValue) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type GetProductReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReq) Reset()         { *m = GetProductReq{} }
func (m *GetProductReq) String() string { return proto.CompactTextString(m) }
func (*GetProductReq) ProtoMessage()    {}
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *GetProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReq.Unmarshal(m, b)
}
func (m *GetProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReq.Marshal(b, m, deterministic)
}
func (m *GetProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReq.Merge(m, src)
}
func (m *GetProductReq) XXX_Size() int {
	return xxx_messageInfo_GetProductReq.Size(m)
}
func (m *GetProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReq proto.InternalMessageInfo

func (m *GetProductReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetProductResp struct {
	Bases                []*ProductBase `protobuf:"bytes,1,rep,name=bases,proto3" json:"bases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProductResp) Reset()         { *m = GetProductResp{} }
func (m *GetProductResp) String() string { return proto.CompactTextString(m) }
func (*GetProductResp) ProtoMessage()    {}
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *GetProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResp.Unmarshal(m, b)
}
func (m *GetProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResp.Marshal(b, m, deterministic)
}
func (m *GetProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResp.Merge(m, src)
}
func (m *GetProductResp) XXX_Size() int {
	return xxx_messageInfo_GetProductResp.Size(m)
}
func (m *GetProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResp proto.InternalMessageInfo

func (m *GetProductResp) GetBases() []*ProductBase {
	if m != nil {
		return m.Bases
	}
	return nil
}

type GetProductCategoryReq struct {
	ProductCategoryId    int64    `protobuf:"varint,1,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductCategoryReq) Reset()         { *m = GetProductCategoryReq{} }
func (m *GetProductCategoryReq) String() string { return proto.CompactTextString(m) }
func (*GetProductCategoryReq) ProtoMessage()    {}
func (*GetProductCategoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *GetProductCategoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductCategoryReq.Unmarshal(m, b)
}
func (m *GetProductCategoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductCategoryReq.Marshal(b, m, deterministic)
}
func (m *GetProductCategoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductCategoryReq.Merge(m, src)
}
func (m *GetProductCategoryReq) XXX_Size() int {
	return xxx_messageInfo_GetProductCategoryReq.Size(m)
}
func (m *GetProductCategoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductCategoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductCategoryReq proto.InternalMessageInfo

func (m *GetProductCategoryReq) GetProductCategoryId() int64 {
	if m != nil {
		return m.ProductCategoryId
	}
	return 0
}

type GetProductCategoryResp struct {
	Categorys            []*ProductCategory `protobuf:"bytes,1,rep,name=categorys,proto3" json:"categorys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetProductCategoryResp) Reset()         { *m = GetProductCategoryResp{} }
func (m *GetProductCategoryResp) String() string { return proto.CompactTextString(m) }
func (*GetProductCategoryResp) ProtoMessage()    {}
func (*GetProductCategoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *GetProductCategoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductCategoryResp.Unmarshal(m, b)
}
func (m *GetProductCategoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductCategoryResp.Marshal(b, m, deterministic)
}
func (m *GetProductCategoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductCategoryResp.Merge(m, src)
}
func (m *GetProductCategoryResp) XXX_Size() int {
	return xxx_messageInfo_GetProductCategoryResp.Size(m)
}
func (m *GetProductCategoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductCategoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductCategoryResp proto.InternalMessageInfo

func (m *GetProductCategoryResp) GetCategorys() []*ProductCategory {
	if m != nil {
		return m.Categorys
	}
	return nil
}

type GetProductDetailReq struct {
	ProductId            int64    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductDetailReq) Reset()         { *m = GetProductDetailReq{} }
func (m *GetProductDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailReq) ProtoMessage()    {}
func (*GetProductDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *GetProductDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailReq.Unmarshal(m, b)
}
func (m *GetProductDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailReq.Marshal(b, m, deterministic)
}
func (m *GetProductDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailReq.Merge(m, src)
}
func (m *GetProductDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailReq.Size(m)
}
func (m *GetProductDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailReq proto.InternalMessageInfo

func (m *GetProductDetailReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

type GetProductDetailResp struct {
	Details              []*ProductDetail `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetProductDetailResp) Reset()         { *m = GetProductDetailResp{} }
func (m *GetProductDetailResp) String() string { return proto.CompactTextString(m) }
func (*GetProductDetailResp) ProtoMessage()    {}
func (*GetProductDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *GetProductDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductDetailResp.Unmarshal(m, b)
}
func (m *GetProductDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductDetailResp.Marshal(b, m, deterministic)
}
func (m *GetProductDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductDetailResp.Merge(m, src)
}
func (m *GetProductDetailResp) XXX_Size() int {
	return xxx_messageInfo_GetProductDetailResp.Size(m)
}
func (m *GetProductDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductDetailResp proto.InternalMessageInfo

func (m *GetProductDetailResp) GetDetails() []*ProductDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type GetProductListReq struct {
	ProductCategoryId    int64    `protobuf:"varint,1,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductListReq) Reset()         { *m = GetProductListReq{} }
func (m *GetProductListReq) String() string { return proto.CompactTextString(m) }
func (*GetProductListReq) ProtoMessage()    {}
func (*GetProductListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{13}
}

func (m *GetProductListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductListReq.Unmarshal(m, b)
}
func (m *GetProductListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductListReq.Marshal(b, m, deterministic)
}
func (m *GetProductListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductListReq.Merge(m, src)
}
func (m *GetProductListReq) XXX_Size() int {
	return xxx_messageInfo_GetProductListReq.Size(m)
}
func (m *GetProductListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductListReq proto.InternalMessageInfo

func (m *GetProductListReq) GetProductCategoryId() int64 {
	if m != nil {
		return m.ProductCategoryId
	}
	return 0
}

type GetProductListResp struct {
	Bases                []*ProductBase `protobuf:"bytes,1,rep,name=bases,proto3" json:"bases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProductListResp) Reset()         { *m = GetProductListResp{} }
func (m *GetProductListResp) String() string { return proto.CompactTextString(m) }
func (*GetProductListResp) ProtoMessage()    {}
func (*GetProductListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{14}
}

func (m *GetProductListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductListResp.Unmarshal(m, b)
}
func (m *GetProductListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductListResp.Marshal(b, m, deterministic)
}
func (m *GetProductListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductListResp.Merge(m, src)
}
func (m *GetProductListResp) XXX_Size() int {
	return xxx_messageInfo_GetProductListResp.Size(m)
}
func (m *GetProductListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductListResp proto.InternalMessageInfo

func (m *GetProductListResp) GetBases() []*ProductBase {
	if m != nil {
		return m.Bases
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductInfo)(nil), "productBase.ProductInfo")
	proto.RegisterType((*ProductBase)(nil), "productBase.ProductBase")
	proto.RegisterType((*ProductCategory)(nil), "productBase.ProductCategory")
	proto.RegisterType((*ProductDetail)(nil), "productBase.ProductDetail")
	proto.RegisterType((*ProductBatch)(nil), "productBase.ProductBatch")
	proto.RegisterType((*ProductAttribute)(nil), "productBase.ProductAttribute")
	proto.RegisterType((*ProductAttributeValue)(nil), "productBase.ProductAttributeValue")
	proto.RegisterType((*GetProductReq)(nil), "productBase.GetProductReq")
	proto.RegisterType((*GetProductResp)(nil), "productBase.GetProductResp")
	proto.RegisterType((*GetProductCategoryReq)(nil), "productBase.GetProductCategoryReq")
	proto.RegisterType((*GetProductCategoryResp)(nil), "productBase.GetProductCategoryResp")
	proto.RegisterType((*GetProductDetailReq)(nil), "productBase.GetProductDetailReq")
	proto.RegisterType((*GetProductDetailResp)(nil), "productBase.GetProductDetailResp")
	proto.RegisterType((*GetProductListReq)(nil), "productBase.GetProductListReq")
	proto.RegisterType((*GetProductListResp)(nil), "productBase.GetProductListResp")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x7e, 0x9d, 0x34, 0x69, 0x33, 0x69, 0xfa, 0x31, 0xfd, 0xd0, 0xbe, 0xa1, 0x2d, 0x66, 0xe1,
	0x90, 0x03, 0xb2, 0x44, 0xe8, 0x01, 0x21, 0x90, 0x80, 0x56, 0x2a, 0x91, 0x0a, 0x2a, 0xe6, 0x43,
	0xea, 0xa9, 0x72, 0xec, 0x85, 0x5a, 0x72, 0x63, 0xd7, 0xbb, 0x41, 0xea, 0x91, 0xbf, 0xc3, 0x1f,
	0x43, 0xe2, 0x0f, 0x70, 0x45, 0x5e, 0xaf, 0xed, 0x75, 0x62, 0xa7, 0xc0, 0x2d, 0x33, 0xf3, 0x3c,
	0x8f, 0x67, 0x66, 0x9f, 0xdd, 0x40, 0x2f, 0x8a, 0x43, 0x6f, 0xea, 0x0a, 0x2b, 0x8a, 0x43, 0x11,
	0x62, 0x57, 0x85, 0xaf, 0x1c, 0xce, 0xe8, 0x0f, 0x03, 0xba, 0x67, 0x69, 0x3c, 0x9a, 0x7c, 0x0e,
	0xf1, 0x21, 0x2c, 0x8d, 0x1d, 0xce, 0x88, 0x61, 0x1a, 0x83, 0xee, 0x90, 0x58, 0x1a, 0xd6, 0x3a,
	0x2b, 0x7e, 0xdb, 0x12, 0x85, 0x8f, 0xa0, 0x3d, 0x76, 0x84, 0x7b, 0xc9, 0x49, 0xc3, 0x6c, 0x0e,
	0xba, 0xc3, 0xff, 0xab, 0xf1, 0xc2, 0xbd, 0xb4, 0x15, 0x10, 0x9f, 0x03, 0x38, 0x42, 0xc4, 0xfe,
	0x78, 0x2a, 0x18, 0x27, 0x4d, 0x49, 0xdb, 0xaf, 0xa2, 0xbd, 0xcc, 0x50, 0xb6, 0x46, 0xc0, 0x27,
	0xb0, 0xe2, 0x3a, 0x82, 0x7d, 0x09, 0xe3, 0x1b, 0xb2, 0x24, 0x7b, 0xdc, 0xab, 0x22, 0x1f, 0x29,
	0x8c, 0x9d, 0xa3, 0xe9, 0xaf, 0x62, 0xd2, 0x04, 0x89, 0x6b, 0xd0, 0xf0, 0x3d, 0x39, 0x67, 0xd3,
	0x6e, 0xf8, 0x1e, 0x9a, 0x90, 0x2d, 0xe6, 0xad, 0x73, 0xc5, 0x48, 0xc3, 0x34, 0x06, 0x1d, 0x5b,
	0x4f, 0x25, 0x08, 0x8f, 0x71, 0x37, 0xf6, 0x23, 0xe1, 0x87, 0x13, 0xd2, 0x4c, 0x11, 0x5a, 0x0a,
	0x77, 0xa1, 0xcd, 0x23, 0xe6, 0xfa, 0x5c, 0xf6, 0xd6, 0xb4, 0x55, 0x94, 0xe4, 0x23, 0xdf, 0xfd,
	0x18, 0x07, 0xa4, 0x25, 0x49, 0x2a, 0xc2, 0x3e, 0xac, 0x84, 0x81, 0xf7, 0x26, 0x9c, 0xb0, 0x1b,
	0xd2, 0x96, 0x8c, 0x3c, 0xc6, 0x6d, 0x68, 0x5d, 0xc9, 0xc2, 0xb2, 0x2c, 0xa4, 0x01, 0x1e, 0x00,
	0x64, 0x13, 0x8d, 0x3c, 0xb2, 0x22, 0x4b, 0x5a, 0x06, 0x11, 0x96, 0x78, 0x18, 0x0b, 0xd2, 0x31,
	0x8d, 0x41, 0xcb, 0x96, 0xbf, 0xe9, 0x39, 0xac, 0xcf, 0xac, 0x65, 0x6e, 0x78, 0x0a, 0xab, 0x99,
	0x88, 0x36, 0x7d, 0x29, 0x97, 0x4b, 0x37, 0x35, 0xe9, 0x6f, 0x06, 0xf4, 0x94, 0xf6, 0x31, 0x13,
	0x8e, 0x1f, 0xe0, 0x10, 0x96, 0xd5, 0xce, 0x16, 0x79, 0x28, 0xf1, 0x9a, 0x9d, 0x01, 0xf1, 0x19,
	0xac, 0xba, 0x97, 0x7e, 0xe0, 0xa9, 0xa2, 0x32, 0x53, 0x3d, 0xb1, 0x84, 0xa6, 0x67, 0xb0, 0xaa,
	0x3b, 0x6d, 0x6e, 0xb6, 0x3d, 0xe8, 0x48, 0xef, 0x69, 0x83, 0x15, 0x89, 0xca, 0xa9, 0xbe, 0x1b,
	0xb0, 0x31, 0xeb, 0xc2, 0x39, 0xd9, 0x07, 0xd0, 0xcb, 0x7d, 0xa9, 0x49, 0x97, 0x93, 0x55, 0xf2,
	0x78, 0x0a, 0xeb, 0x39, 0xe8, 0x93, 0x13, 0x4c, 0x59, 0x62, 0x97, 0x64, 0x62, 0xba, 0xf0, 0x1e,
	0x48, 0xa8, 0x3d, 0x4b, 0xa5, 0xef, 0x60, 0xa7, 0x12, 0x39, 0xd7, 0xf0, 0x36, 0xb4, 0xbe, 0x26,
	0x05, 0xd5, 0x68, 0x1a, 0x54, 0xce, 0x6f, 0x41, 0xef, 0x84, 0x09, 0xa5, 0x6a, 0xb3, 0x6b, 0xdc,
	0x07, 0x50, 0x9d, 0x5d, 0xe4, 0x92, 0x1d, 0x95, 0x19, 0x79, 0xf4, 0x05, 0xac, 0xe9, 0x78, 0x1e,
	0xa1, 0x05, 0xad, 0xe4, 0x81, 0xe0, 0xc4, 0xa8, 0x3f, 0x4a, 0xf9, 0x8e, 0xa4, 0x30, 0x7a, 0x02,
	0x3b, 0x85, 0x42, 0x7e, 0x79, 0xd9, 0x35, 0x5a, 0xb0, 0x95, 0x7d, 0x39, 0x33, 0x63, 0xd1, 0xc2,
	0x66, 0x54, 0x26, 0x8c, 0x3c, 0xfa, 0x01, 0x76, 0xab, 0x84, 0x78, 0x84, 0x4f, 0xa1, 0x93, 0x29,
	0x64, 0x6d, 0x2d, 0x7e, 0x3a, 0x0a, 0x38, 0x3d, 0x84, 0xad, 0x42, 0x35, 0x35, 0xfa, 0x1f, 0xac,
	0xe5, 0x14, 0xb6, 0xe7, 0x59, 0x3c, 0xc2, 0x43, 0x58, 0xf6, 0x64, 0x94, 0xf5, 0xd1, 0xaf, 0xea,
	0x43, 0x11, 0x32, 0x28, 0x3d, 0x82, 0xcd, 0x42, 0xed, 0xd4, 0xe7, 0xe2, 0x5f, 0xd6, 0x73, 0x0c,
	0x38, 0x2b, 0xf2, 0xf7, 0xa7, 0x35, 0xfc, 0xd9, 0x80, 0x35, 0x95, 0x7e, 0xed, 0x4c, 0xbc, 0x80,
	0xc5, 0x78, 0x02, 0x50, 0x08, 0x63, 0x79, 0xa0, 0x92, 0x97, 0xfa, 0x77, 0x6a, 0x6b, 0x3c, 0xa2,
	0xff, 0xe1, 0x85, 0xde, 0x61, 0xfe, 0x5e, 0xd1, 0x1a, 0x92, 0x66, 0x95, 0xfe, 0xfd, 0x5b, 0x31,
	0xf2, 0x03, 0xe7, 0xb0, 0x31, 0x7b, 0x2a, 0x68, 0xd6, 0x50, 0xf3, 0xa3, 0xee, 0xdf, 0xbb, 0x05,
	0x21, 0xa5, 0xdf, 0xeb, 0xf7, 0x20, 0xd9, 0x2e, 0x1e, 0xd4, 0xd0, 0xd4, 0xf9, 0xf5, 0xef, 0x2e,
	0xac, 0x27, 0xa2, 0xe3, 0xb6, 0xfc, 0xd7, 0x7e, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x83,
	0x0f, 0xc9, 0xc6, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductHandlerClient is the client API for ProductHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductHandlerClient interface {
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
	GetProductCategory(ctx context.Context, in *GetProductCategoryReq, opts ...grpc.CallOption) (*GetProductCategoryResp, error)
	GetProductDetail(ctx context.Context, in *GetProductDetailReq, opts ...grpc.CallOption) (*GetProductDetailResp, error)
	GetProductList(ctx context.Context, in *GetProductListReq, opts ...grpc.CallOption) (*GetProductListResp, error)
}

type productHandlerClient struct {
	cc *grpc.ClientConn
}

func NewProductHandlerClient(cc *grpc.ClientConn) ProductHandlerClient {
	return &productHandlerClient{cc}
}

func (c *productHandlerClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	out := new(GetProductResp)
	err := c.cc.Invoke(ctx, "/productBase.ProductHandler/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productHandlerClient) GetProductCategory(ctx context.Context, in *GetProductCategoryReq, opts ...grpc.CallOption) (*GetProductCategoryResp, error) {
	out := new(GetProductCategoryResp)
	err := c.cc.Invoke(ctx, "/productBase.ProductHandler/GetProductCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productHandlerClient) GetProductDetail(ctx context.Context, in *GetProductDetailReq, opts ...grpc.CallOption) (*GetProductDetailResp, error) {
	out := new(GetProductDetailResp)
	err := c.cc.Invoke(ctx, "/productBase.ProductHandler/GetProductDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productHandlerClient) GetProductList(ctx context.Context, in *GetProductListReq, opts ...grpc.CallOption) (*GetProductListResp, error) {
	out := new(GetProductListResp)
	err := c.cc.Invoke(ctx, "/productBase.ProductHandler/GetProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductHandlerServer is the server API for ProductHandler service.
type ProductHandlerServer interface {
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
	GetProductCategory(context.Context, *GetProductCategoryReq) (*GetProductCategoryResp, error)
	GetProductDetail(context.Context, *GetProductDetailReq) (*GetProductDetailResp, error)
	GetProductList(context.Context, *GetProductListReq) (*GetProductListResp, error)
}

// UnimplementedProductHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedProductHandlerServer struct {
}

func (*UnimplementedProductHandlerServer) GetProduct(ctx context.Context, req *GetProductReq) (*GetProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductHandlerServer) GetProductCategory(ctx context.Context, req *GetProductCategoryReq) (*GetProductCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCategory not implemented")
}
func (*UnimplementedProductHandlerServer) GetProductDetail(ctx context.Context, req *GetProductDetailReq) (*GetProductDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductDetail not implemented")
}
func (*UnimplementedProductHandlerServer) GetProductList(ctx context.Context, req *GetProductListReq) (*GetProductListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductList not implemented")
}

func RegisterProductHandlerServer(s *grpc.Server, srv ProductHandlerServer) {
	s.RegisterService(&_ProductHandler_serviceDesc, srv)
}

func _ProductHandler_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductHandlerServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productBase.ProductHandler/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductHandlerServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductHandler_GetProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductHandlerServer).GetProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productBase.ProductHandler/GetProductCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductHandlerServer).GetProductCategory(ctx, req.(*GetProductCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductHandler_GetProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductHandlerServer).GetProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productBase.ProductHandler/GetProductDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductHandlerServer).GetProductDetail(ctx, req.(*GetProductDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductHandler_GetProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductHandlerServer).GetProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productBase.ProductHandler/GetProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductHandlerServer).GetProductList(ctx, req.(*GetProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "productBase.ProductHandler",
	HandlerType: (*ProductHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductHandler_GetProduct_Handler,
		},
		{
			MethodName: "GetProductCategory",
			Handler:    _ProductHandler_GetProductCategory_Handler,
		},
		{
			MethodName: "GetProductDetail",
			Handler:    _ProductHandler_GetProductDetail_Handler,
		},
		{
			MethodName: "GetProductList",
			Handler:    _ProductHandler_GetProductList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
