// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"catering/product/internal/logic"
	"catering/product/internal/svc"
	pb "catering/proto/product"
)

type ProductHandlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewProductHandlerServer(svcCtx *svc.ServiceContext) *ProductHandlerServer {
	return &ProductHandlerServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductHandlerServer) GetProduct(ctx context.Context, in *pb.GetProductReq) (*pb.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductHandlerServer) GetProductCategory(ctx context.Context, in *pb.GetProductCategoryReq) (*pb.GetProductCategoryResp, error) {
	l := logic.NewGetProductCategoryLogic(ctx, s.svcCtx)
	return l.GetProductCategory(in)
}

func (s *ProductHandlerServer) GetProductDetail(ctx context.Context, in *pb.GetProductDetailReq) (*pb.GetProductDetailResp, error) {
	l := logic.NewGetProductDetailLogic(ctx, s.svcCtx)
	return l.GetProductDetail(in)
}

func (s *ProductHandlerServer) GetProductList(ctx context.Context, in *pb.GetProductListReq) (*pb.GetProductListResp, error) {
	l := logic.NewGetProductListLogic(ctx, s.svcCtx)
	return l.GetProductList(in)
}
