// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"catering/area/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/area/provinces",
				Handler: provinceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/area/citys",
				Handler: cityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/area/distincts",
				Handler: distinctHandler(serverCtx),
			},
		},
	)
}
